flowchart LR
    resource0["end"]
    resource1["#96;**same label**#96;"]
    resource2["#96;**same label**#96;"]
    resource3["api #34;quoted#34; [brackets] (parentheses) #35;quot; #38; #60;script#62; #92;   next"]
    resource0 --> resource3
