//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AddCommandStrings", typeof(AddCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding Aspire hosting integration....
        /// </summary>
        public static string AddingAspireIntegration {
            get {
                return ResourceManager.GetString("AddingAspireIntegration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include all integrations, even those not marked compatible with the AppHost language.
        /// </summary>
        public static string AllArgumentDescription {
            get {
                return ResourceManager.GetString("AllArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a hosting integration to the AppHost.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the package: {0}.
        /// </summary>
        public static string ErrorOccurredWhileAddingPackage {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileAddingPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching integrations: {0}.
        /// </summary>
        public static string ErrorOccurredWhileSearchingIntegrations {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileSearchingIntegrations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json).
        /// </summary>
        public static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} integration package(s)..
        /// </summary>
        public static string FoundIntegrationPackages {
            get {
                return ResourceManager.GetString("FoundIntegrationPackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} integration package(s) matching &apos;{1}&apos;..
        /// </summary>
        public static string FoundIntegrationPackagesMatchingSearchTerm {
            get {
                return ResourceManager.GetString("FoundIntegrationPackagesMatchingSearchTerm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string HeaderPackage {
            get {
                return ResourceManager.GetString("HeaderPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string HeaderVersion {
            get {
                return ResourceManager.GetString("HeaderVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the integration to add (e.g. redis, postgres).
        /// </summary>
        public static string IntegrationArgumentDescription {
            get {
                return ResourceManager.GetString("IntegrationArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Aspire hosting integrations.
        /// </summary>
        public static string IntegrationCommandDescription {
            get {
                return ResourceManager.GetString("IntegrationCommandDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List available Aspire hosting integrations.
        /// </summary>
        public static string IntegrationListDescription {
            get {
                return ResourceManager.GetString("IntegrationListDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; integration is not available for {1} AppHosts because it does not expose a compatible API surface. Use --all to add it anyway..
        /// </summary>
        public static string IntegrationNotPolyglotCompatible {
            get {
                return ResourceManager.GetString("IntegrationNotPolyglotCompatible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire AppHost project file, or a directory to search, for channel-aware integration discovery.
        /// </summary>
        public static string IntegrationSearchAppHostOptionDescription {
            get {
                return ResourceManager.GetString("IntegrationSearchAppHostOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search available Aspire hosting integrations.
        /// </summary>
        public static string IntegrationSearchDescription {
            get {
                return ResourceManager.GetString("IntegrationSearchDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The integration search query..
        /// </summary>
        public static string IntegrationSearchQueryArgumentDescription {
            get {
                return ResourceManager.GetString("IntegrationSearchQueryArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No integration packages were found. Please check your internet connection or NuGet source configuration..
        /// </summary>
        public static string NoIntegrationPackagesFound {
            get {
                return ResourceManager.GetString("NoIntegrationPackagesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No integration packages matched &apos;{0}&apos;..
        /// </summary>
        public static string NoIntegrationPackagesMatchedSearchTerm {
            get {
                return ResourceManager.GetString("NoIntegrationPackagesMatchedSearchTerm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No exact match was found for &apos;{0}&apos;. In non-interactive mode the integration name must exactly match a package id or friendly name; fuzzy fallback is disabled to prevent silently selecting the wrong package..
        /// </summary>
        public static string NonInteractiveRequiresExactPackageMatch {
            get {
                return ResourceManager.GetString("NonInteractiveRequiresExactPackageMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No packages found..
        /// </summary>
        public static string NoPackagesFound {
            get {
                return ResourceManager.GetString("NoPackagesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No packages matched your search term &apos;{0}&apos;. Showing all available packages..
        /// </summary>
        public static string NoPackagesMatchedSearchTerm {
            get {
                return ResourceManager.GetString("NoPackagesMatchedSearchTerm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No integrations compatible with this AppHost language were found. Use --all to list all integrations..
        /// </summary>
        public static string NoPolyglotCompatibleIntegrationsFound {
            get {
                return ResourceManager.GetString("NoPolyglotCompatibleIntegrationsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The package {0}::{1} was added successfully..
        /// </summary>
        public static string PackageAddedSuccessfully {
            get {
                return ResourceManager.GetString("PackageAddedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The package installation failed with exit code {0}..
        /// </summary>
        public static string PackageInstallationFailed {
            get {
                return ResourceManager.GetString("PackageInstallationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} integration(s) not compatible with this AppHost language were hidden. Use --all to show them..
        /// </summary>
        public static string PolyglotIntegrationsHidden {
            get {
                return ResourceManager.GetString("PolyglotIntegrationsHidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire AppHost project file, or a directory to search, to add the integration to.
        /// </summary>
        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for Aspire integrations....
        /// </summary>
        public static string SearchingForAspirePackages {
            get {
                return ResourceManager.GetString("SearchingForAspirePackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for version &apos;{1}&apos; of {0}....
        /// </summary>
        public static string SearchingForSpecifiedPackageVersion {
            get {
                return ResourceManager.GetString("SearchingForSpecifiedPackageVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an integration to add:.
        /// </summary>
        public static string SelectAnIntegrationToAdd {
            get {
                return ResourceManager.GetString("SelectAnIntegrationToAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a version of {0}:.
        /// </summary>
        public static string SelectAVersionOfPackage {
            get {
                return ResourceManager.GetString("SelectAVersionOfPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The NuGet source to use for the integration.
        /// </summary>
        public static string SourceArgumentDescription {
            get {
                return ResourceManager.GetString("SourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested version &apos;{1}&apos; was not found for package &apos;{0}&apos;..
        /// </summary>
        public static string SpecifiedVersionNotFoundForPackage {
            get {
                return ResourceManager.GetString("SpecifiedVersionNotFoundForPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When --version is specified in non-interactive mode, the integration name must exactly match a package or friendly name. No exact match was found for &apos;{0}&apos;..
        /// </summary>
        public static string SpecifiedVersionRequiresExactPackageMatch {
            get {
                return ResourceManager.GetString("SpecifiedVersionRequiresExactPackageMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopped a running Aspire AppHost instance to allow package modification..
        /// </summary>
        public static string StoppedRunningInstance {
            get {
                return ResourceManager.GetString("StoppedRunningInstance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to stop one or more running Aspire AppHost instances. Please stop the application and try again..
        /// </summary>
        public static string UnableToStopRunningInstances {
            get {
                return ResourceManager.GetString("UnableToStopRunningInstances", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected number of packages found..
        /// </summary>
        public static string UnexpectedNumberOfPackagesFound {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfPackagesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use pre-release packages.
        /// </summary>
        public static string UsePrereleasePackages {
            get {
                return ResourceManager.GetString("UsePrereleasePackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The version of the integration to add.
        /// </summary>
        public static string VersionArgumentDescription {
            get {
                return ResourceManager.GetString("VersionArgumentDescription", resourceCulture);
            }
        }
    }
}
