//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ApiCommandStrings", typeof(ApiCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API item &apos;{0}&apos; not found. Use &apos;aspire docs api search&apos; or &apos;aspire docs api list &lt;scope&gt;&apos; to find available identifiers..
        /// </summary>
        internal static string ApiNotFound {
            get {
                return ResourceManager.GetString("ApiNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse and search Aspire API reference documentation from aspire.dev.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json).
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} API entries under &apos;{1}&apos;..
        /// </summary>
        internal static string FoundApiEntries {
            get {
                return ResourceManager.GetString("FoundApiEntries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found {0} API results for &apos;{1}&apos;..
        /// </summary>
        internal static string FoundSearchResults {
            get {
                return ResourceManager.GetString("FoundSearchResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get the markdown for an API reference item by its identifier.
        /// </summary>
        internal static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string HeaderGroup {
            get {
                return ResourceManager.GetString("HeaderGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string HeaderId {
            get {
                return ResourceManager.GetString("HeaderId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string HeaderKind {
            get {
                return ResourceManager.GetString("HeaderKind", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string HeaderLanguage {
            get {
                return ResourceManager.GetString("HeaderLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string HeaderScore {
            get {
                return ResourceManager.GetString("HeaderScore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The API identifier (for example, &apos;csharp/aspire.azure.ai.inference/aspireazureaiinferenceextensions&apos;).
        /// </summary>
        internal static string IdArgumentDescription {
            get {
                return ResourceManager.GetString("IdArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Limit results to a specific API language.
        /// </summary>
        internal static string LanguageOptionDescription {
            get {
                return ResourceManager.GetString("LanguageOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum number of search results to return (default: 5, max: 10).
        /// </summary>
        internal static string LimitOptionDescription {
            get {
                return ResourceManager.GetString("LimitOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List API entries under a parent scope.
        /// </summary>
        internal static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading API documentation....
        /// </summary>
        internal static string LoadingApiDocumentation {
            get {
                return ResourceManager.GetString("LoadingApiDocumentation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No API entries found under &apos;{0}&apos;..
        /// </summary>
        internal static string NoApiEntriesFound {
            get {
                return ResourceManager.GetString("NoApiEntriesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No API results found for &apos;{0}&apos;. Try different search terms..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The search query.
        /// </summary>
        internal static string QueryArgumentDescription {
            get {
                return ResourceManager.GetString("QueryArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The parent API scope to browse (for example, &apos;csharp&apos; or &apos;typescript/aspire.hosting.azure.appconfiguration&apos;).
        /// </summary>
        internal static string ScopeArgumentDescription {
            get {
                return ResourceManager.GetString("ScopeArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Aspire API reference documentation by keywords.
        /// </summary>
        internal static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
    }
}
