//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleActivityLoggerStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleActivityLoggerStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ConsoleActivityLoggerStrings", typeof(ConsoleActivityLoggerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string ActivityStarting {
            get {
                return ResourceManager.GetString("ActivityStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        internal static string ActivityStartingWithName {
            get {
                return ResourceManager.GetString("ActivityStartingWithName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pipeline failed.
        /// </summary>
        internal static string PipelineFailed {
            get {
                return ResourceManager.GetString("PipelineFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pipeline succeeded.
        /// </summary>
        internal static string PipelineSucceeded {
            get {
                return ResourceManager.GetString("PipelineSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} failed.
        /// </summary>
        internal static string SummaryFailed {
            get {
                return ResourceManager.GetString("SummaryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For more details, add --pipeline-log-level debug/trace to the command..
        /// </summary>
        internal static string SummaryLogLevelHelp {
            get {
                return ResourceManager.GetString("SummaryLogLevelHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} steps succeeded.
        /// </summary>
        internal static string SummaryStepsSucceeded {
            get {
                return ResourceManager.GetString("SummaryStepsSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} steps succeeded.
        /// </summary>
        internal static string SummaryStepsSucceededWithTotal {
            get {
                return ResourceManager.GetString("SummaryStepsSucceededWithTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total time: {0}.
        /// </summary>
        internal static string SummaryTotalTime {
            get {
                return ResourceManager.GetString("SummaryTotalTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} warnings.
        /// </summary>
        internal static string SummaryWarningsPlural {
            get {
                return ResourceManager.GetString("SummaryWarningsPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} warning.
        /// </summary>
        internal static string SummaryWarningsSingular {
            get {
                return ResourceManager.GetString("SummaryWarningsSingular", resourceCulture);
            }
        }
    }
}
