//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.DashboardCommandStrings", typeof(DashboardCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow anonymous access to the dashboard.
        /// </summary>
        public static string AllowAnonymousOptionDescription {
            get {
                return ResourceManager.GetString("AllowAnonymousOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The application name displayed in the dashboard and used to scope persisted dashboard data.
        /// </summary>
        public static string ApplicationNameOptionDescription {
            get {
                return ResourceManager.GetString("ApplicationNameOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;aspire dashboard&apos; command requires the CLI bundle, but no bundle layout was found. The bundle provides the dashboard binary and supporting files. Run &apos;aspire setup --force&apos; to extract the bundle, or reinstall the Aspire CLI..
        /// </summary>
        public static string BundleLayoutNotFound {
            get {
                return ResourceManager.GetString("BundleLayoutNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire dashboard requires the CLI bundle. The bundle was not found..
        /// </summary>
        public static string BundleNotAvailable {
            get {
                return ResourceManager.GetString("BundleNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path for a JSON configuration file.
        /// </summary>
        public static string ConfigFilePathOptionDescription {
            get {
                return ResourceManager.GetString("ConfigFilePathOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard could not start because a configured port is already in use. Use a different port or stop the conflicting process..
        /// </summary>
        public static string DashboardExitedAddressInUse {
            get {
                return ResourceManager.GetString("DashboardExitedAddressInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard exited unexpectedly due to an error. See logs for details..
        /// </summary>
        public static string DashboardExitedUnexpectedError {
            get {
                return ResourceManager.GetString("DashboardExitedUnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard configuration is invalid. Check the provided options and try again..
        /// </summary>
        public static string DashboardExitedValidationFailure {
            get {
                return ResourceManager.GetString("DashboardExitedValidationFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard exited with exit code {0}..
        /// </summary>
        public static string DashboardExitedWithError {
            get {
                return ResourceManager.GetString("DashboardExitedWithError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start Aspire dashboard: {0}.
        /// </summary>
        public static string DashboardFailedToStart {
            get {
                return ResourceManager.GetString("DashboardFailedToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardLabel {
            get {
                return ResourceManager.GetString("DashboardLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard started (PID {0})..
        /// </summary>
        public static string DashboardStarted {
            get {
                return ResourceManager.GetString("DashboardStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard did not become ready within the expected time..
        /// </summary>
        public static string DashboardStartTimedOut {
            get {
                return ResourceManager.GetString("DashboardStartTimedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage the Aspire dashboard (Preview).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preparing dashboard bits....
        /// </summary>
        public static string EnsuringDashboardBundle {
            get {
                return ResourceManager.GetString("EnsuringDashboardBundle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more HTTP endpoints through which the dashboard frontend is served.
        /// </summary>
        public static string FrontendUrlOptionDescription {
            get {
                return ResourceManager.GetString("FrontendUrlOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogsLabel {
            get {
                return ResourceManager.GetString("LogsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CLI bundle layout was found, but the Dashboard executable is missing. The bundle may be corrupted or incomplete. Run &apos;aspire setup --force&apos; to re-extract the bundle, or reinstall the Aspire CLI..
        /// </summary>
        public static string ManagedBinaryNotFound {
            get {
                return ResourceManager.GetString("ManagedBinaryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OTLP/gRPC.
        /// </summary>
        public static string OtlpGrpcLabel {
            get {
                return ResourceManager.GetString("OtlpGrpcLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The OTLP/gRPC endpoint. This endpoint hosts an OTLP service and receives telemetry using gRPC.
        /// </summary>
        public static string OtlpGrpcUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpGrpcUrlOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OTLP/HTTP.
        /// </summary>
        public static string OtlpHttpLabel {
            get {
                return ResourceManager.GetString("OtlpHttpLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The OTLP/HTTP endpoint. This endpoint hosts an OTLP service and receives telemetry using Protobuf over HTTP.
        /// </summary>
        public static string OtlpHttpUrlOptionDescription {
            get {
                return ResourceManager.GetString("OtlpHttpUrlOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The dashboard data persistence mode: None, Run, or Resume.
        /// </summary>
        public static string PersistenceModeOptionDescription {
            get {
                return ResourceManager.GetString("PersistenceModeOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the Aspire dashboard (Preview).
        /// </summary>
        public static string RunDescription {
            get {
                return ResourceManager.GetString("RunDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting dashboard....
        /// </summary>
        public static string StartingDashboard {
            get {
                return ResourceManager.GetString("StartingDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopping dashboard..
        /// </summary>
        public static string StoppingDashboard {
            get {
                return ResourceManager.GetString("StoppingDashboard", resourceCulture);
            }
        }
    }
}
