//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already connected to AppHost backchannel..
        /// </summary>
        public static string AlreadyConnectedToBackchannel {
            get {
                return ResourceManager.GetString("AlreadyConnectedToBackchannel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost is incompatible with the CLI. The AppHost must be updated to a version that supports the {0} capability..
        /// </summary>
        public static string AppHostIncompatibleWithCli {
            get {
                return ResourceManager.GetString("AppHostIncompatibleWithCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No buildable AppHosts were found, but there may have been unbuildable AppHosts..
        /// </summary>
        public static string AppHostsMayNotBeBuildable {
            get {
                return ResourceManager.GetString("AppHostsMayNotBeBuildable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost file was specified in &apos;{0}&apos; but it does not exist at &apos;{1}&apos;..
        /// </summary>
        public static string AppHostWasSpecifiedButDoesntExist {
            get {
                return ResourceManager.GetString("AppHostWasSpecifiedButDoesntExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AspireHostingVersion is null.
        /// </summary>
        public static string AspireHostingVersionNull {
            get {
                return ResourceManager.GetString("AspireHostingVersionNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire.Hosting package version {0} is not supported. Please update to the latest version..
        /// </summary>
        public static string AspireSDKVersionNotSupported {
            get {
                return ResourceManager.GetString("AspireSDKVersionNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot use --watch and --no-build at the same time..
        /// </summary>
        public static string CantUseBothWatchAndNoBuild {
            get {
                return ResourceManager.GetString("CantUseBothWatchAndNoBuild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate HTTPS development certificate (result: {0})..
        /// </summary>
        public static string CertificateGenerationFailed {
            get {
                return ResourceManager.GetString("CertificateGenerationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer certificates may not be fully trusted (trust exit code was: {0})..
        /// </summary>
        public static string CertificatesMayNotBeFullyTrusted {
            get {
                return ResourceManager.GetString("CertificatesMayNotBeFullyTrusted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer certificates are not trusted. Trust them interactively by running &apos;aspire certs trust&apos;..
        /// </summary>
        public static string CertificatesNotTrustedNonInteractive {
            get {
                return ResourceManager.GetString("CertificatesNotTrustedNonInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer certificates are only partially trusted. Trust them interactively by running &apos;aspire certs trust&apos;..
        /// </summary>
        public static string CertificatesPartiallyTrustedNonInteractive {
            get {
                return ResourceManager.GetString("CertificatesPartiallyTrustedNonInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostic details:.
        /// </summary>
        public static string CodegenDebugHeader {
            get {
                return ResourceManager.GetString("CodegenDebugHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run with &apos;--debug&apos; for full diagnostic details..
        /// </summary>
        public static string CodegenDebugHint {
            get {
                return ResourceManager.GetString("CodegenDebugHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} SDK code generation failed because the installed Aspire CLI appears to be incompatible with the configured Aspire SDK. Run &apos;aspire update&apos; to align the CLI and SDK and try again..
        /// </summary>
        public static string CodegenIncompatibleSdkSummary {
            get {
                return ResourceManager.GetString("CodegenIncompatibleSdkSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The installed Aspire CLI version ({0}) differs from the Aspire SDK version ({1}) used for code generation. If you run into errors, update the Aspire CLI to match or exceed the SDK version..
        /// </summary>
        public static string CodegenVersionSkewWarning {
            get {
                return ResourceManager.GetString("CodegenVersionSkewWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This command is not yet supported with single file AppHosts..
        /// </summary>
        public static string CommandNotSupportedWithSingleFileAppHost {
            get {
                return ResourceManager.GetString("CommandNotSupportedWithSingleFileAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration file &apos;{0}&apos; must contain a JSON object..
        /// </summary>
        public static string ConfigurationFileMustBeJsonObject {
            get {
                return ResourceManager.GetString("ConfigurationFileMustBeJsonObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration key {0} not found..
        /// </summary>
        public static string ConfigurationKeyNotFound {
            get {
                return ResourceManager.GetString("ConfigurationKeyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration key is required..
        /// </summary>
        public static string ConfigurationKeyRequired {
            get {
                return ResourceManager.GetString("ConfigurationKeyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration value is required..
        /// </summary>
        public static string ConfigurationValueRequired {
            get {
                return ResourceManager.GetString("ConfigurationValueRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configured AppHost path in &apos;{0}&apos; (&apos;{1}&apos;) is empty or contains characters that are not allowed in a file path..
        /// </summary>
        public static string ConfiguredAppHostPathHasInvalidCharacters {
            get {
                return ResourceManager.GetString("ConfiguredAppHostPathHasInvalidCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configured AppHost path in &apos;{0}&apos; (&apos;{1}&apos;) must be a JSON string..
        /// </summary>
        public static string ConfiguredAppHostPathMustBeString {
            get {
                return ResourceManager.GetString("ConfiguredAppHostPathMustBeString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not parse Aspire.Hosting package version..
        /// </summary>
        public static string CouldNotParseAspireSDKVersion {
            get {
                return ResourceManager.GetString("CouldNotParseAspireSDKVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: Required .NET SDK not found; .NET AppHost projects may be missing from results..
        /// </summary>
        public static string DotNetSdkUnavailableAppHostDiscoveryWarning {
            get {
                return ResourceManager.GetString("DotNetSdkUnavailableAppHostDiscoveryWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error deleting configuration: {0}.
        /// </summary>
        public static string ErrorDeletingConfiguration {
            get {
                return ResourceManager.GetString("ErrorDeletingConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error setting configuration: {0}.
        /// </summary>
        public static string ErrorSettingConfiguration {
            get {
                return ResourceManager.GetString("ErrorSettingConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire Extension is incompatible with the CLI. The Extension must be updated to a version that supports the {0} capability..
        /// </summary>
        public static string ExtensionIncompatibleWithCli {
            get {
                return ResourceManager.GetString("ExtensionIncompatibleWithCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire extension token must be set if ASPIRE_EXTENSION_ENDPOINT is set. Please ensure that ASPIRE_EXTENSION_TOKEN is set.
        /// </summary>
        public static string ExtensionTokenMustBeSet {
            get {
                return ResourceManager.GetString("ExtensionTokenMustBeSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse package search results..
        /// </summary>
        public static string FailedToParsePackageSearchResults {
            get {
                return ResourceManager.GetString("FailedToParsePackageSearchResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse template version from stdout..
        /// </summary>
        public static string FailedToParseTemplateVersionFromStdout {
            get {
                return ResourceManager.GetString("FailedToParseTemplateVersionFromStdout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve all Aspire packages via cache..
        /// </summary>
        public static string FailedToRetrieveCachedAllAspirePackages {
            get {
                return ResourceManager.GetString("FailedToRetrieveCachedAllAspirePackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve template packages via cache..
        /// </summary>
        public static string FailedToRetrieveCachedTemplatePackages {
            get {
                return ResourceManager.GetString("FailedToRetrieveCachedTemplatePackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to search for packages. Exit code: {0}..
        /// </summary>
        public static string FailedToSearchForPackages {
            get {
                return ResourceManager.GetString("FailedToSearchForPackages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The AppHost path cannot be set in global settings. Use &apos;appHost.path&apos; in a local aspire.config.json file instead..
        /// </summary>
        public static string GlobalAppHostPathCannotBeSetWithConfigCommand {
            get {
                return ResourceManager.GetString("GlobalAppHostPathCannotBeSetWithConfigCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global settings file &apos;{0}&apos; contains &apos;{1}&apos;, which is not supported. AppHost paths must be configured locally..
        /// </summary>
        public static string GlobalAppHostPathIgnored {
            get {
                return ResourceManager.GetString("GlobalAppHostPathIgnored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The integration project could not be built..
        /// </summary>
        public static string IntegrationBuildFailed {
            get {
                return ResourceManager.GetString("IntegrationBuildFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The integration project could not be built because a referenced project requires a newer version of Aspire.Hosting than this Aspire CLI ({0}) provides. The AppHost server is the CLI itself, so project references in aspire.config.json must target the same version the CLI ships. Either use an Aspire CLI that matches the referenced projects, or reference published packages instead of local projects..
        /// </summary>
        public static string IntegrationBuildPackageDowngradeFailed {
            get {
                return ResourceManager.GetString("IntegrationBuildPackageDowngradeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration file &apos;{0}&apos; contains invalid JSON: {1}.
        /// </summary>
        public static string InvalidJsonInConfigFile {
            get {
                return ResourceManager.GetString("InvalidJsonInConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid locale {0} provided will not be used..
        /// </summary>
        public static string InvalidLocaleProvided {
            get {
                return ResourceManager.GetString("InvalidLocaleProvided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The provided extension socket path needs two valid parts..
        /// </summary>
        public static string InvalidSocketPath {
            get {
                return ResourceManager.GetString("InvalidSocketPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The legacy AppHost path key &apos;appHostPath&apos; cannot be set with &apos;aspire config set&apos;. Use &apos;appHost.path&apos; in a local aspire.config.json file instead..
        /// </summary>
        public static string LegacyAppHostPathCannotBeSetWithConfigCommand {
            get {
                return ResourceManager.GetString("LegacyAppHostPathCannotBeSetWithConfigCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This project uses the legacy &apos;apphost.ts&apos; layout. Run &apos;aspire update --migrate&apos; to upgrade to the recommended &apos;apphost.mts&apos; format. The legacy layout continues to work — this is a non-blocking warning..
        /// </summary>
        public static string LegacyTypeScriptAppHostWarning {
            get {
                return ResourceManager.GetString("LegacyTypeScriptAppHostWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to C# AppHost requires .NET SDK version {0} or later. Detected: {1}..
        /// </summary>
        public static string MinimumSdkVersionNotMet {
            get {
                return ResourceManager.GetString("MinimumSdkVersionNotMet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple project files found..
        /// </summary>
        public static string MultipleProjectFilesFound {
            get {
                return ResourceManager.GetString("MultipleProjectFilesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No project file found..
        /// </summary>
        public static string NoProjectFileFound {
            get {
                return ResourceManager.GetString("NoProjectFileFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input was required for prompt &apos;{0}&apos; but not provided..
        /// </summary>
        public static string NoSelectionMade {
            get {
                return ResourceManager.GetString("NoSelectionMade", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project could not be analyzed due to a build error. See logs at {0}.
        /// </summary>
        public static string ProjectCouldNotBeAnalyzed {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeAnalyzed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project file does not exist..
        /// </summary>
        public static string ProjectFileDoesntExist {
            get {
                return ResourceManager.GetString("ProjectFileDoesntExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not build: {0}.
        /// </summary>
        public static string ProjectFileMayBeUnbuildableAppHost {
            get {
                return ResourceManager.GetString("ProjectFileMayBeUnbuildableAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project file is not an Aspire AppHost project..
        /// </summary>
        public static string ProjectFileNotAppHostProject {
            get {
                return ResourceManager.GetString("ProjectFileNotAppHostProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project files were created, but Aspire could not run &apos;{0}&apos; automatically because the required JavaScript tooling was not found on PATH. You may see missing package errors or red squiggles in your IDE until you install {1} and run &apos;{0}&apos; in the project directory..
        /// </summary>
        public static string ProjectFilesCreatedButNodeToolsNotFound {
            get {
                return ResourceManager.GetString("ProjectFilesCreatedButNodeToolsNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project is not supported in the current environment: {0}.
        /// </summary>
        public static string ProjectFileUnsupportedInCurrentEnvironment {
            get {
                return ResourceManager.GetString("ProjectFileUnsupportedInCurrentEnvironment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project does not contain an Aspire AppHost..
        /// </summary>
        public static string ProjectIsNotAppHost {
            get {
                return ResourceManager.GetString("ProjectIsNotAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SDK API export cannot export {0} because that package supplies the selected language&apos;s code generator instead of an integration API surface..
        /// </summary>
        public static string SdkExportGeneratorPackageNotExportable {
            get {
                return ResourceManager.GetString("SdkExportGeneratorPackageNotExportable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SDK API export is not supported for {0} because it does not use a code generator..
        /// </summary>
        public static string SdkExportLanguageDoesNotSupportCodeGeneration {
            get {
                return ResourceManager.GetString("SdkExportLanguageDoesNotSupportCodeGeneration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single file AppHost feature is not enabled. To use .cs AppHost files, enable the feature using configuration..
        /// </summary>
        public static string SingleFileAppHostFeatureNotEnabled {
            get {
                return ResourceManager.GetString("SingleFileAppHostFeatureNotEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the assembly version..
        /// </summary>
        public static string UnableToRetrieveAssemblyVersion {
            get {
                return ResourceManager.GetString("UnableToRetrieveAssemblyVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported locale {0} provided will not be used. Supported locales are: {1}..
        /// </summary>
        public static string UnsupportedLocaleProvided {
            get {
                return ResourceManager.GetString("UnsupportedLocaleProvided", resourceCulture);
            }
        }
    }
}
