//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpGroupStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpGroupStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.HelpGroupStrings", typeof(HelpGroupStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App commands:.
        /// </summary>
        internal static string AppCommands {
            get {
                return ResourceManager.GetString("AppCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment:.
        /// </summary>
        internal static string Deployment {
            get {
                return ResourceManager.GetString("Deployment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use &quot;aspire &lt;command&gt; --help&quot; for more information about a command..
        /// </summary>
        internal static string HelpHint {
            get {
                return ResourceManager.GetString("HelpHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitoring:.
        /// </summary>
        internal static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other commands:.
        /// </summary>
        internal static string OtherCommands {
            get {
                return ResourceManager.GetString("OtherCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource management:.
        /// </summary>
        internal static string ResourceManagement {
            get {
                return ResourceManager.GetString("ResourceManagement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tools &amp; configuration:.
        /// </summary>
        internal static string ToolsAndConfiguration {
            get {
                return ResourceManager.GetString("ToolsAndConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to aspire &lt;command&gt; [options].
        /// </summary>
        internal static string UsageSyntax {
            get {
                return ResourceManager.GetString("UsageSyntax", resourceCulture);
            }
        }
    }
}
