//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoOptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoOptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.InfoOptionStrings", typeof(InfoOptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Aspire CLI version, channel, installation, and hive information..
        /// </summary>
        public static string InfoOptionDescription {
            get {
                return ResourceManager.GetString("InfoOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the information output format..
        /// </summary>
        public static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspire CLI.
        /// </summary>
        public static string InfoHeading {
            get {
                return ResourceManager.GetString("InfoHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installations.
        /// </summary>
        public static string InstallationsHeading {
            get {
                return ResourceManager.GetString("InstallationsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation {0}.
        /// </summary>
        public static string InstallationHeadingFormat {
            get {
                return ResourceManager.GetString("InstallationHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan hive.
        /// </summary>
        public static string OrphanHiveHeading {
            get {
                return ResourceManager.GetString("OrphanHiveHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation discovery.
        /// </summary>
        public static string DiscoveryFailureHeading {
            get {
                return ResourceManager.GetString("DiscoveryFailureHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string ChannelLabel {
            get {
                return ResourceManager.GetString("ChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceLabel {
            get {
                return ResourceManager.GetString("SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canonical path.
        /// </summary>
        public static string CanonicalPathLabel {
            get {
                return ResourceManager.GetString("CanonicalPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hive.
        /// </summary>
        public static string HiveLabel {
            get {
                return ResourceManager.GetString("HiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH status.
        /// </summary>
        public static string PathStatusLabel {
            get {
                return ResourceManager.GetString("PathStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ReasonLabel {
            get {
                return ResourceManager.GetString("ReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string StatusOk {
            get {
                return ResourceManager.GetString("StatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not probed.
        /// </summary>
        public static string StatusNotProbed {
            get {
                return ResourceManager.GetString("StatusNotProbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No install found.
        /// </summary>
        public static string StatusNoInstallFound {
            get {
                return ResourceManager.GetString("StatusNoInstallFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string PathStatusActive {
            get {
                return ResourceManager.GetString("PathStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowed.
        /// </summary>
        public static string PathStatusShadowed {
            get {
                return ResourceManager.GetString("PathStatusShadowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on PATH.
        /// </summary>
        public static string PathStatusNotOnPath {
            get {
                return ResourceManager.GetString("PathStatusNotOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install discovery failed. See the Aspire CLI logs for details..
        /// </summary>
        public static string InstallationDiscoveryFailedReason {
            get {
                return ResourceManager.GetString("InstallationDiscoveryFailedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install discovery timed out after {0} seconds. See the Aspire CLI logs for details..
        /// </summary>
        public static string InstallationDiscoveryTimedOutReasonFormat {
            get {
                return ResourceManager.GetString("InstallationDiscoveryTimedOutReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The --self option can only be used with --info..
        /// </summary>
        public static string SelfRequiresInfo {
            get {
                return ResourceManager.GetString("SelfRequiresInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The --format option can only be used with --info..
        /// </summary>
        public static string FormatRequiresInfo {
            get {
                return ResourceManager.GetString("FormatRequiresInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --info option cannot be combined with a subcommand..
        /// </summary>
        public static string InfoCannotBeCombinedWithSubcommand {
            get {
                return ResourceManager.GetString("InfoCannotBeCombinedWithSubcommand", resourceCulture);
            }
        }
    }
}
