//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InitCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InitCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.InitCommandStrings", typeof(InitCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding AppHost project to solution....
        /// </summary>
        internal static string AddingAppHostProjectToSolution {
            get {
                return ResourceManager.GetString("AddingAppHostProjectToSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding projects to solution....
        /// </summary>
        internal static string AddingProjectsToSolution {
            get {
                return ResourceManager.GetString("AddingProjectsToSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adding ServiceDefaults project to solution....
        /// </summary>
        internal static string AddingServiceDefaultsProjectToSolution {
            get {
                return ResourceManager.GetString("AddingServiceDefaultsProjectToSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire AppHost created! To complete setup, run:.
        /// </summary>
        internal static string AppHostCreatedRunOne {
            get {
                return ResourceManager.GetString("AppHostCreatedRunOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire AppHost created! To complete setup, run one of:.
        /// </summary>
        internal static string AppHostCreatedRunOneOf {
            get {
                return ResourceManager.GetString("AppHostCreatedRunOneOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire initialization complete!.
        /// </summary>
        internal static string AspireInitializationComplete {
            get {
                return ResourceManager.GetString("AspireInitializationComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created {0}.
        /// </summary>
        internal static string CreatedFile {
            get {
                return ResourceManager.GetString("CreatedFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating AppHost from template....
        /// </summary>
        internal static string CreatingAppHostFromTemplate {
            get {
                return ResourceManager.GetString("CreatingAppHostFromTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating AppHost project....
        /// </summary>
        internal static string CreatingAppHostProject {
            get {
                return ResourceManager.GetString("CreatingAppHostProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating ServiceDefaults project....
        /// </summary>
        internal static string CreatingServiceDefaultsProject {
            get {
                return ResourceManager.GetString("CreatingServiceDefaultsProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to `aspire init {0}` is deprecated and no longer affects generated AppHosts. It is accepted for compatibility and will be removed in a future version..
        /// </summary>
        internal static string DeprecatedOptionWarning {
            get {
                return ResourceManager.GetString("DeprecatedOptionWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initialize Aspire in an existing codebase.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create AppHost from template (exit code {0})..
        /// </summary>
        internal static string FailedToCreateAppHostFromTemplate {
            get {
                return ResourceManager.GetString("FailedToCreateAppHostFromTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to parse existing {0} at &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string FailedToParseExistingConfig {
            get {
                return ResourceManager.GetString("FailedToParseExistingConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} already exists — skipping..
        /// </summary>
        internal static string FileAlreadyExistsSkipping {
            get {
                return ResourceManager.GetString("FileAlreadyExistsSkipping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create apphost.cs in the current directory, skipping .NET solution discovery. Requires C#..
        /// </summary>
        internal static string FileBasedOptionDescription {
            get {
                return ResourceManager.GetString("FileBasedOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --file-based option requires C#. Select --language csharp or omit --file-based..
        /// </summary>
        internal static string FileBasedRequiresCSharp {
            get {
                return ResourceManager.GetString("FileBasedRequiresCSharp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fix or remove {0} and re-run `aspire init`..
        /// </summary>
        internal static string FixOrRemoveConfigAndRerun {
            get {
                return ResourceManager.GetString("FixOrRemoveConfigAndRerun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installing Aspire project templates....
        /// </summary>
        internal static string InstallingAspireProjectTemplates {
            get {
                return ResourceManager.GetString("InstallingAspireProjectTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The programming language for the AppHost (csharp, typescript).
        /// </summary>
        internal static string LanguageOptionDescription {
            get {
                return ResourceManager.GetString("LanguageOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple solution files found. Please select which one to add the Aspire projects to:.
        /// </summary>
        internal static string MultipleSolutionsFound {
            get {
                return ResourceManager.GetString("MultipleSolutionsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No solution file found. Creating single-file AppHost....
        /// </summary>
        internal static string NoSolutionFoundCreatingSingleFileAppHost {
            get {
                return ResourceManager.GetString("NoSolutionFoundCreatingSingleFileAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolving template version....
        /// </summary>
        internal static string ResolvingTemplateVersion {
            get {
                return ResourceManager.GetString("ResolvingTemplateVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Solution has already been initialized with Aspire..
        /// </summary>
        internal static string SolutionAlreadyInitialized {
            get {
                return ResourceManager.GetString("SolutionAlreadyInitialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The solution file &apos;{0}&apos; and project file &apos;{1}&apos; are in the same directory. The AppHost and ServiceDefaults projects cannot be created inside an existing project directory. Move the solution file to a parent directory or the project file to a subdirectory..
        /// </summary>
        internal static string SolutionAndProjectInSameDirectory {
            get {
                return ResourceManager.GetString("SolutionAndProjectInSameDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Solution detected: {0}.
        /// </summary>
        internal static string SolutionDetected {
            get {
                return ResourceManager.GetString("SolutionDetected", resourceCulture);
            }
        }
    }
}
