//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogsCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogsCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.LogsCommandStrings", typeof(LogsCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display logs from resources in a running AppHost.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stream logs in real-time as they are written.
        /// </summary>
        public static string FollowOptionDescription {
            get {
                return ResourceManager.GetString("FollowOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Getting logs....
        /// </summary>
        public static string GettingLogs {
            get {
                return ResourceManager.GetString("GettingLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include hidden resources in the output.
        /// </summary>
        public static string IncludeHiddenOptionDescription {
            get {
                return ResourceManager.GetString("IncludeHiddenOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json).
        /// </summary>
        public static string JsonOptionDescription {
            get {
                return ResourceManager.GetString("JsonOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No logs found..
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No resources found..
        /// </summary>
        public static string NoResourcesFound {
            get {
                return ResourceManager.GetString("NoResourcesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the resource to get logs for. If not specified, logs from all resources are shown..
        /// </summary>
        public static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A resource name is required when not using --follow. Use --follow to stream logs from all resources..
        /// </summary>
        public static string ResourceRequiredWithoutFollow {
            get {
                return ResourceManager.GetString("ResourceRequiredWithoutFollow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full-text search to filter log content. See https://aka.ms/aspire/cli-search for more details.
        /// </summary>
        public static string SearchOptionDescription {
            get {
                return ResourceManager.GetString("SearchOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to stream logs from.
        /// </summary>
        public static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --tail value must be a positive number..
        /// </summary>
        public static string TailMustBePositive {
            get {
                return ResourceManager.GetString("TailMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of lines to show from the end of logs (default: all).
        /// </summary>
        public static string TailOptionDescription {
            get {
                return ResourceManager.GetString("TailOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --tail option requires a resource name to be specified..
        /// </summary>
        public static string TailRequiresResource {
            get {
                return ResourceManager.GetString("TailRequiresResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show timestamps for each log line.
        /// </summary>
        public static string TimestampsOptionDescription {
            get {
                return ResourceManager.GetString("TimestampsOptionDescription", resourceCulture);
            }
        }
    }
}
