//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.NewCommandStrings", typeof(NewCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel to use for templates (stable, daily).
        /// </summary>
        public static string ChannelOptionDescription {
            get {
                return ResourceManager.GetString("ChannelOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel to use for templates (stable, staging, daily).
        /// </summary>
        public static string ChannelOptionDescriptionWithStaging {
            get {
                return ResourceManager.GetString("ChannelOptionDescriptionWithStaging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directly in the selected folder.
        /// </summary>
        public static string CreateProjectDirectlyInSelectedFolderChoice {
            get {
                return ResourceManager.GetString("CreateProjectDirectlyInSelectedFolderChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In a subdirectory named &apos;{0}&apos; in the selected folder.
        /// </summary>
        public static string CreateProjectNameSubdirectoryChoice {
            get {
                return ResourceManager.GetString("CreateProjectNameSubdirectoryChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new app from an Aspire starter template.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the output path.
        /// </summary>
        public static string EnterTheOutputPath {
            get {
                return ResourceManager.GetString("EnterTheOutputPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the project name.
        /// </summary>
        public static string EnterTheProjectName {
            get {
                return ResourceManager.GetString("EnterTheProjectName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid project name..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The programming language for the AppHost.
        /// </summary>
        public static string LanguageOptionDescription {
            get {
                return ResourceManager.GetString("LanguageOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the project to create.
        /// </summary>
        public static string NameArgumentDescription {
            get {
                return ResourceManager.GetString("NameArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No channel found matching &apos;{0}&apos;. Valid options are: {1}..
        /// </summary>
        public static string NoChannelFoundMatching {
            get {
                return ResourceManager.GetString("NoChannelFoundMatching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matching local Aspire.ProjectTemplates package was found for Aspire CLI version &apos;{0}&apos;. Build and stage matching packages with localhive.sh (macOS/Linux) or localhive.ps1 (Windows), set ASPIRE_CLI_PACKAGES to a directory containing the package, or explicitly choose feed-backed templates with --channel, --source, or --version..
        /// </summary>
        public static string NoMatchingLocalTemplatePackage {
            get {
                return ResourceManager.GetString("NoMatchingLocalTemplatePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A template must be specified when running in non-interactive mode. Use &apos;aspire new &lt;template&gt;&apos;..
        /// </summary>
        public static string NonInteractiveTemplateRequired {
            get {
                return ResourceManager.GetString("NonInteractiveTemplateRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No package channels are available..
        /// </summary>
        public static string NoPackageChannelsAvailable {
            get {
                return ResourceManager.GetString("NoPackageChannelsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No template versions found in channel &apos;{0}&apos;..
        /// </summary>
        public static string NoTemplateVersionsFoundInChannel {
            get {
                return ResourceManager.GetString("NoTemplateVersionsFoundInChannel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output path for the project.
        /// </summary>
        public static string OutputArgumentDescription {
            get {
                return ResourceManager.GetString("OutputArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output directory &apos;{0}&apos; already exists and is not empty. Specify a different location..
        /// </summary>
        public static string OutputDirectoryNotEmptyInteractive {
            get {
                return ResourceManager.GetString("OutputDirectoryNotEmptyInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output directory &apos;{0}&apos; already exists and is not empty. Specify --output with a different location..
        /// </summary>
        public static string OutputDirectoryNotEmptyNonInteractive {
            get {
                return ResourceManager.GetString("OutputDirectoryNotEmptyNonInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output path &apos;{0}&apos; contains invalid characters..
        /// </summary>
        public static string OutputPathContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("OutputPathContainsInvalidCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolving template version....
        /// </summary>
        public static string ResolvingTemplateVersion {
            get {
                return ResourceManager.GetString("ResolvingTemplateVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a template:.
        /// </summary>
        public static string SelectAProjectTemplate {
            get {
                return ResourceManager.GetString("SelectAProjectTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a template version:.
        /// </summary>
        public static string SelectATemplateVersion {
            get {
                return ResourceManager.GetString("SelectATemplateVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Where do you want the project to be created?.
        /// </summary>
        public static string SelectProjectCreationLocation {
            get {
                return ResourceManager.GetString("SelectProjectCreationLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The NuGet source to use for the project templates.
        /// </summary>
        public static string SourceArgumentDescription {
            get {
                return ResourceManager.GetString("SourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local NuGet source directory &apos;{0}&apos; does not exist..
        /// </summary>
        public static string SourceDirectoryNotFound {
            get {
                return ResourceManager.GetString("SourceDirectoryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --source URL includes credentials, a query string, or a fragment and cannot be written to the project&apos;s NuGet.config. Configure credentials with NuGet credential providers or user-level NuGet configuration, then pass the feed URL without embedded secrets..
        /// </summary>
        public static string SourceWithCredentialsCannotBePersisted {
            get {
                return ResourceManager.GetString("SourceWithCredentialsCannotBePersisted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (use pre-release templates).
        /// </summary>
        public static string UsePrereleaseTemplates {
            get {
                return ResourceManager.GetString("UsePrereleaseTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The version of the project templates to use.
        /// </summary>
        public static string VersionArgumentDescription {
            get {
                return ResourceManager.GetString("VersionArgumentDescription", resourceCulture);
            }
        }
    }
}
