//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ResourceCommandStrings", typeof(ResourceCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; argument is required..
        /// </summary>
        internal static string ArgumentRequired {
            get {
                return ResourceManager.GetString("ArgumentRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available resource commands:.
        /// </summary>
        internal static string AvailableResourceCommands {
            get {
                return ResourceManager.GetString("AvailableResourceCommands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execute a command on a resource (e.g. start, stop, restart).
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the command to execute (e.g. start, stop, restart).
        /// </summary>
        internal static string CommandNameArgumentDescription {
            get {
                return ResourceManager.GetString("CommandNameArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the resource to execute the command on.
        /// </summary>
        internal static string CommandResourceArgumentDescription {
            get {
                return ResourceManager.GetString("CommandResourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allowed values: {0}..
        /// </summary>
        internal static string CommandSpecificHelpAllowedValues {
            get {
                return ResourceManager.GetString("CommandSpecificHelpAllowedValues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Command options:.
        /// </summary>
        internal static string CommandSpecificHelpCommandOptions {
            get {
                return ResourceManager.GetString("CommandSpecificHelpCommandOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default: {0}..
        /// </summary>
        internal static string CommandSpecificHelpDefaultValue {
            get {
                return ResourceManager.GetString("CommandSpecificHelpDefaultValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use `-- --{0}{1}` to pass this command option..
        /// </summary>
        internal static string CommandSpecificHelpDelimiterHint {
            get {
                return ResourceManager.GetString("CommandSpecificHelpDelimiterHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        internal static string CommandSpecificHelpRequired {
            get {
                return ResourceManager.GetString("CommandSpecificHelpRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to aspire resource {0} {1} [options] [[--] &lt;command-options&gt;...].
        /// </summary>
        internal static string CommandSpecificHelpUsageSyntax {
            get {
                return ResourceManager.GetString("CommandSpecificHelpUsageSyntax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string CommandSpecificHelpValuePlaceholder {
            get {
                return ResourceManager.GetString("CommandSpecificHelpValuePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to connect to.
        /// </summary>
        internal static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }
    }
}
