//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RunCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RunCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.RunCommandStrings", typeof(RunCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maybe later.
        /// </summary>
        public static string AgentConfigurationMaybeLater {
            get {
                return ResourceManager.GetString("AgentConfigurationMaybeLater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AgentConfigurationNo {
            get {
                return ResourceManager.GetString("AgentConfigurationNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire has detected {0} agentic coding environment(s) to configure. Would you like to configure now?.
        /// </summary>
        public static string AgentConfigurationPrompt {
            get {
                return ResourceManager.GetString("AgentConfigurationPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select agent environments to configure:.
        /// </summary>
        public static string AgentConfigurationSelectPrompt {
            get {
                return ResourceManager.GetString("AgentConfigurationSelectPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AgentConfigurationYes {
            get {
                return ResourceManager.GetString("AgentConfigurationYes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost.
        /// </summary>
        public static string AppHost {
            get {
                return ResourceManager.GetString("AppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection to the child AppHost was lost. Waiting for the AppHost process to exit. Press Ctrl+C to stop waiting..
        /// </summary>
        public static string AppHostConnectionLostWaitingForExit {
            get {
                return ResourceManager.GetString("AppHostConnectionLostWaitingForExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost process exited with code {0}..
        /// </summary>
        public static string AppHostExitedWithCode {
            get {
                return ResourceManager.GetString("AppHostExitedWithCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost failed to build..
        /// </summary>
        public static string AppHostFailedToBuild {
            get {
                return ResourceManager.GetString("AppHostFailedToBuild", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppHost started successfully..
        /// </summary>
        public static string AppHostStartedSuccessfully {
            get {
                return ResourceManager.GetString("AppHostStartedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check logs for details: {0}.
        /// </summary>
        public static string CheckLogsForDetails {
            get {
                return ResourceManager.GetString("CheckLogsForDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to AppHost....
        /// </summary>
        public static string ConnectingToAppHost {
            get {
                return ResourceManager.GetString("ConnectingToAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copying user secrets for isolated mode....
        /// </summary>
        public static string CopyingUserSecrets {
            get {
                return ResourceManager.GetString("CopyingUserSecrets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aspire Dashboard failed to start or is disabled..
        /// </summary>
        public static string DashboardFailedToStart {
            get {
                return ResourceManager.GetString("DashboardFailedToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run an Aspire AppHost interactively for development.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run the AppHost in the background and exit after it starts.
        /// </summary>
        public static string DetachArgumentDescription {
            get {
                return ResourceManager.GetString("DetachArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endpoints.
        /// </summary>
        public static string Endpoints {
            get {
                return ResourceManager.GetString("Endpoints", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to start the AppHost..
        /// </summary>
        public static string FailedToStartAppHost {
            get {
                return ResourceManager.GetString("FailedToStartAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop any running instance of the AppHost without prompting.
        /// </summary>
        public static string ForceArgumentDescription {
            get {
                return ResourceManager.GetString("ForceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --format option can only be used together with --detach..
        /// </summary>
        public static string FormatRequiresDetach {
            get {
                return ResourceManager.GetString("FormatRequiresDetach", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The health of the resource, eg Healthy.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} environment variable must be a positive number of seconds..
        /// </summary>
        public static string InvalidAppHostStartupTimeoutEnvironmentVariable {
            get {
                return ResourceManager.GetString("InvalidAppHostStartupTimeoutEnvironmentVariable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IsCompatibleAppHost is null.
        /// </summary>
        public static string IsCompatibleAppHostIsNull {
            get {
                return ResourceManager.GetString("IsCompatibleAppHostIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run in isolated mode with randomized ports and isolated user secrets, allowing multiple instances to run simultaneously.
        /// </summary>
        public static string IsolatedArgumentDescription {
            get {
                return ResourceManager.GetString("IsolatedArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A running instance of this AppHost was found and will be stopped. To run multiple isolated instances simultaneously, run from different directories such as git worktree directories..
        /// </summary>
        public static string IsolatedModeRunningInstanceWarning {
            get {
                return ResourceManager.GetString("IsolatedModeRunningInstanceWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format for detached AppHost results.
        /// </summary>
        public static string JsonArgumentDescription {
            get {
                return ResourceManager.GetString("JsonArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do not build or restore the project before running.
        /// </summary>
        public static string NoBuildArgumentDescription {
            get {
                return ResourceManager.GetString("NoBuildArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --no-build option cannot be used when watch mode is enabled..
        /// </summary>
        public static string NoBuildNotSupportedWithWatchMode {
            get {
                return ResourceManager.GetString("NoBuildNotSupportedWithWatchMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press [bold]CTRL+C[/] to stop the AppHost and exit..
        /// </summary>
        public static string PressCtrlCToStopAppHost {
            get {
                return ResourceManager.GetString("PressCtrlCToStopAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path to the Aspire AppHost project file or a directory to search.
        /// </summary>
        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project could not be run. See logs at {0}.
        /// </summary>
        public static string ProjectCouldNotBeRun {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeRun", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent AppHost startup output.
        /// </summary>
        public static string RecentAppHostStartupOutput {
            get {
                return ResourceManager.GetString("RecentAppHostStartupOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running instance stopped successfully..
        /// </summary>
        public static string RunningInstanceStopped {
            get {
                return ResourceManager.GetString("RunningInstanceStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether to start a debug session, if running in an Aspire Terminal.
        /// </summary>
        public static string StartDebugSessionArgumentDescription {
            get {
                return ResourceManager.GetString("StartDebugSessionArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting Aspire AppHost....
        /// </summary>
        public static string StartingAppHost {
            get {
                return ResourceManager.GetString("StartingAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting Aspire AppHost in the background....
        /// </summary>
        public static string StartingAppHostInBackground {
            get {
                return ResourceManager.GetString("StartingAppHostInBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting dashboard....
        /// </summary>
        public static string StartingDashboard {
            get {
                return ResourceManager.GetString("StartingDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detected aspire {0} inside the Aspire extension, starting a debug session in VS Code....
        /// </summary>
        public static string StartingDebugSessionInExtension {
            get {
                return ResourceManager.GetString("StartingDebugSessionInExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detected aspire {0} inside the Aspire extension, running app in VS Code. To start a debug session, add --start-debug-session..
        /// </summary>
        public static string StartingRunSessionInExtension {
            get {
                return ResourceManager.GetString("StartingRunSessionInExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting {0}s for AppHost to start. If the AppHost is still building or starting, set {1} to a higher value and try again..
        /// </summary>
        public static string TimeoutWaitingForAppHost {
            get {
                return ResourceManager.GetString("TimeoutWaitingForAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for AppHost to start....
        /// </summary>
        public static string WaitingForAppHostToStart {
            get {
                return ResourceManager.GetString("WaitingForAppHostToStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start project resources in watch mode.
        /// </summary>
        public static string WatchArgumentDescription {
            get {
                return ResourceManager.GetString("WatchArgumentDescription", resourceCulture);
            }
        }
    }
}
