//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecretCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecretCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.SecretCommandStrings", typeof(SecretCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find an AppHost project..
        /// </summary>
        internal static string CouldNotFindAppHost {
            get {
                return ResourceManager.GetString("CouldNotFindAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete a secret.
        /// </summary>
        internal static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage AppHost user secrets.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get a secret value.
        /// </summary>
        internal static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The secret key (e.g., Azure:Location or Parameters:postgres-password).
        /// </summary>
        internal static string KeyArgumentDescription {
            get {
                return ResourceManager.GetString("KeyArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyColumnHeader {
            get {
                return ResourceManager.GetString("KeyColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The secret key to delete.
        /// </summary>
        internal static string KeyDeleteArgumentDescription {
            get {
                return ResourceManager.GetString("KeyDeleteArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The secret key to retrieve.
        /// </summary>
        internal static string KeyRetrieveArgumentDescription {
            get {
                return ResourceManager.GetString("KeyRetrieveArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List all secrets.
        /// </summary>
        internal static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No secrets configured..
        /// </summary>
        internal static string NoSecretsConfigured {
            get {
                return ResourceManager.GetString("NoSecretsConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show the secrets file path..
        /// </summary>
        internal static string PathDescription {
            get {
                return ResourceManager.GetString("PathDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; deleted successfully..
        /// </summary>
        internal static string SecretDeleteSuccess {
            get {
                return ResourceManager.GetString("SecretDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; not found..
        /// </summary>
        internal static string SecretNotFound {
            get {
                return ResourceManager.GetString("SecretNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; set successfully..
        /// </summary>
        internal static string SecretSetSuccess {
            get {
                return ResourceManager.GetString("SecretSetSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set a secret value.
        /// </summary>
        internal static string SetDescription {
            get {
                return ResourceManager.GetString("SetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The secret value to set.
        /// </summary>
        internal static string ValueArgumentDescription {
            get {
                return ResourceManager.GetString("ValueArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueColumnHeader {
            get {
                return ResourceManager.GetString("ValueColumnHeader", resourceCulture);
            }
        }
    }
}
