//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.SharedCommandStrings", typeof(SharedCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suppress AI agent environment configuration after project creation.
        /// </summary>
        internal static string AgentInitOptionDescription {
            get {
                return ResourceManager.GetString("AgentInitOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No running AppHost found. Use &apos;aspire run&apos; to start one first..
        /// </summary>
        internal static string AppHostNotRunning {
            get {
                return ResourceManager.GetString("AppHostNotRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No AppHost is currently running for &apos;{0}&apos;. Use &apos;aspire run&apos; to start it first..
        /// </summary>
        internal static string AppHostNotRunningAtPath {
            get {
                return ResourceManager.GetString("AppHostNotRunningAtPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No running AppHost found in the current worktree. Use &apos;--apphost &lt;path&gt;&apos; to target one directly, or &apos;--all&apos; to include AppHosts from other worktrees..
        /// </summary>
        internal static string AppHostNotRunningInCurrentWorktree {
            get {
                return ResourceManager.GetString("AppHostNotRunningInCurrentWorktree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path to the Aspire AppHost project file or a directory to search.
        /// </summary>
        internal static string AppHostOptionDescription {
            get {
                return ResourceManager.GetString("AppHostOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format for detached AppHost results.
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string HeaderLanguage {
            get {
                return ResourceManager.GetString("HeaderLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string HeaderPath {
            get {
                return ResourceManager.GetString("HeaderPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include hidden resources in the output.
        /// </summary>
        internal static string IncludeHiddenOptionDescription {
            get {
                return ResourceManager.GetString("IncludeHiddenOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run in isolated mode with randomized ports and isolated user secrets, allowing multiple instances to run simultaneously.
        /// </summary>
        internal static string IsolatedOptionDescription {
            get {
                return ResourceManager.GetString("IsolatedOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --launch-profile option is not supported for {0} AppHosts..
        /// </summary>
        internal static string LaunchProfileNotSupported {
            get {
                return ResourceManager.GetString("LaunchProfileNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The .NET launch profile to use when starting the AppHost.
        /// </summary>
        internal static string LaunchProfileOptionDescription {
            get {
                return ResourceManager.GetString("LaunchProfileOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include all candidate AppHosts, ignoring .gitignore and built-in directory filters.
        /// </summary>
        internal static string LsAllOptionDescription {
            get {
                return ResourceManager.GetString("LsAllOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List candidate AppHost project files in the workspace (use `aspire ps` for running resources).
        /// </summary>
        internal static string LsCommandDescription {
            get {
                return ResourceManager.GetString("LsCommandDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json).
        /// </summary>
        internal static string LsFormatOptionDescription {
            get {
                return ResourceManager.GetString("LsFormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No candidate AppHosts found..
        /// </summary>
        internal static string LsNoCandidateAppHostsFound {
            get {
                return ResourceManager.GetString("LsNoCandidateAppHostsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for Aspire AppHosts. {0} directories searched. {1} AppHosts found....
        /// </summary>
        internal static string LsSearchingForAppHostsStatus {
            get {
                return ResourceManager.GetString("LsSearchingForAppHostsStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output discovered AppHosts as newline-delimited JSON. Requires --format json.
        /// </summary>
        internal static string LsStreamOptionDescription {
            get {
                return ResourceManager.GetString("LsStreamOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --stream option requires --format json..
        /// </summary>
        internal static string LsStreamRequiresJson {
            get {
                return ResourceManager.GetString("LsStreamRequiresJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple running AppHosts were found, but the CLI is running in non-interactive mode. Pass --apphost to specify which AppHost to use..
        /// </summary>
        internal static string MultipleAppHostsNonInteractive {
            get {
                return ResourceManager.GetString("MultipleAppHostsNonInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple running AppHosts found in the current directory. Select from running AppHosts..
        /// </summary>
        internal static string MultipleInScopeAppHosts {
            get {
                return ResourceManager.GetString("MultipleInScopeAppHosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No running AppHosts found in the current directory. Select from all running AppHosts..
        /// </summary>
        internal static string NoInScopeAppHostsShowingAll {
            get {
                return ResourceManager.GetString("NoInScopeAppHostsShowingAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} command requires --yes when the --non-interactive option is specified..
        /// </summary>
        internal static string NonInteractiveRequiresYesFormat {
            get {
                return ResourceManager.GetString("NonInteractiveRequiresYesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The environment to use for the operation. The default is &apos;Production&apos;..
        /// </summary>
        internal static string PipelineEnvironmentOptionDescription {
            get {
                return ResourceManager.GetString("PipelineEnvironmentOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set the output format..
        /// </summary>
        internal static string PipelineFormatOptionDescription {
            get {
                return ResourceManager.GetString("PipelineFormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --format option can only be used together with --list-steps..
        /// </summary>
        internal static string PipelineFormatRequiresListSteps {
            get {
                return ResourceManager.GetString("PipelineFormatRequiresListSteps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include exception details (stack traces) in pipeline logs.
        /// </summary>
        internal static string PipelineIncludeExceptionDetailsOptionDescription {
            get {
                return ResourceManager.GetString("PipelineIncludeExceptionDetailsOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List registered pipeline steps without running lifecycle callbacks or pipeline steps..
        /// </summary>
        internal static string PipelineListStepsOptionDescription {
            get {
                return ResourceManager.GetString("PipelineListStepsOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set the minimum log level for pipeline logging (trace, debug, information, warning, error, critical). The default is &apos;information&apos;..
        /// </summary>
        internal static string PipelineLogLevelOptionDescription {
            get {
                return ResourceManager.GetString("PipelineLogLevelOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steps Summary:.
        /// </summary>
        internal static string PipelineStepsSummaryTitle {
            get {
                return ResourceManager.GetString("PipelineStepsSummaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step timeline:.
        /// </summary>
        internal static string PipelineStepTimelineLabel {
            get {
                return ResourceManager.GetString("PipelineStepTimelineLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Would you like to configure AI agent environments for this project?.
        /// </summary>
        internal static string PromptRunAgentInit {
            get {
                return ResourceManager.GetString("PromptRunAgentInit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning for running AppHosts....
        /// </summary>
        internal static string ScanningForRunningAppHosts {
            get {
                return ResourceManager.GetString("ScanningForRunningAppHosts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an AppHost to {0}:.
        /// </summary>
        internal static string SelectAppHost {
            get {
                return ResourceManager.GetString("SelectAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unrecognized option &apos;{0}&apos;. Did you mean &apos;{1}&apos;?.
        /// </summary>
        internal static string UnrecognizedOptionDidYouMeanFormat {
            get {
                return ResourceManager.GetString("UnrecognizedOptionDidYouMeanFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using AppHost: {0}.
        /// </summary>
        internal static string UsingAppHost {
            get {
                return ResourceManager.GetString("UsingAppHost", resourceCulture);
            }
        }
    }
}
