//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StopCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StopCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.StopCommandStrings", typeof(StopCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} options cannot be used together..
        /// </summary>
        public static string AllAndProjectMutuallyExclusive {
            get {
                return ResourceManager.GetString("AllAndProjectMutuallyExclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop all running AppHosts.
        /// </summary>
        public static string AllOptionDescription {
            get {
                return ResourceManager.GetString("AllOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple AppHost connections match PID {0}. No AppHosts were stopped..
        /// </summary>
        public static string AmbiguousAppHostPid {
            get {
                return ResourceManager.GetString("AmbiguousAppHostPid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (PID {1}).
        /// </summary>
        public static string AppHostIdentifierWithProcessId {
            get {
                return ResourceManager.GetString("AppHostIdentifierWithProcessId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No running AppHost at &apos;{0}&apos; with PID {1} was found. No AppHosts were stopped..
        /// </summary>
        public static string AppHostNotRunningAtPathWithPid {
            get {
                return ResourceManager.GetString("AppHostNotRunningAtPathWithPid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No running AppHost with PID {0} was found. No AppHosts were stopped..
        /// </summary>
        public static string AppHostNotRunningWithPid {
            get {
                return ResourceManager.GetString("AppHostNotRunningWithPid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} stopped successfully..
        /// </summary>
        public static string AppHostStoppedSuccessfully {
            get {
                return ResourceManager.GetString("AppHostStoppedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cleaning up persistent resources for {0}....
        /// </summary>
        public static string CleaningPersistentResources {
            get {
                return ResourceManager.GetString("CleaningPersistentResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not determine the AppHost project path..
        /// </summary>
        public static string CouldNotDetermineAppHostPath {
            get {
                return ResourceManager.GetString("CouldNotDetermineAppHostPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not inspect the AppHost project to verify persistent resource cleanup compatibility. Persistent resource cleanup will still be attempted..
        /// </summary>
        public static string DcpCleanupCompatibilityCheckFailed {
            get {
                return ResourceManager.GetString("DcpCleanupCompatibilityCheckFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DCP cleanup exited with code {0}..
        /// </summary>
        public static string DcpCleanupExitCode {
            get {
                return ResourceManager.GetString("DcpCleanupExitCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to clean up persistent resources for {0}. {1}.
        /// </summary>
        public static string DcpCleanupFailed {
            get {
                return ResourceManager.GetString("DcpCleanupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find the DCP executable needed to clean up persistent resources..
        /// </summary>
        public static string DcpCleanupUnavailable {
            get {
                return ResourceManager.GetString("DcpCleanupUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This AppHost uses Aspire.Hosting {0}, which might not support persistent resource cleanup. Persistent resource cleanup requires Aspire.Hosting {1} or later, or an AppHost configured to use the Aspire CLI bundle. Persistent resource cleanup will still be attempted..
        /// </summary>
        public static string DcpCleanupUnsupportedAppHostVersion {
            get {
                return ResourceManager.GetString("DcpCleanupUnsupportedAppHostVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This AppHost uses Aspire.Hosting {0}, which might not support persistent volume cleanup. Persistent volume cleanup requires Aspire.Hosting {1} or later, or an AppHost configured to use the Aspire CLI bundle. Persistent volume cleanup will still be attempted..
        /// </summary>
        public static string DcpVolumeCleanupUnsupportedAppHostVersion {
            get {
                return ResourceManager.GetString("DcpVolumeCleanupUnsupportedAppHostVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop a running AppHost.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to stop {0}..
        /// </summary>
        public static string FailedToStopAppHost {
            get {
                return ResourceManager.GetString("FailedToStopAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the AppHost and clean up its persistent resources, preserving volumes by default.
        /// </summary>
        public static string ForceOptionDescription {
            get {
                return ResourceManager.GetString("ForceOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found running AppHost: {0}.
        /// </summary>
        public static string FoundRunningAppHost {
            get {
                return ResourceManager.GetString("FoundRunningAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple AppHosts are running. Use {0} to specify which one to stop, or use {1} to stop all of them..
        /// </summary>
        public static string MultipleAppHostsNonInteractive {
            get {
                return ResourceManager.GetString("MultipleAppHostsNonInteractive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple AppHosts are running. Use --apphost to specify which one to stop, or select one:.
        /// </summary>
        public static string MultipleAppHostsRunning {
            get {
                return ResourceManager.GetString("MultipleAppHostsRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Persistent resources for {0} cleaned up..
        /// </summary>
        public static string PersistentResourcesCleaned {
            get {
                return ResourceManager.GetString("PersistentResourcesCleaned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --pid option must be a positive integer..
        /// </summary>
        public static string PidMustBePositive {
            get {
                return ResourceManager.GetString("PidMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop only the AppHost with this positive process ID (not the CLI process ID). With --apphost, the project file path must also match exactly. Cannot be combined with --all or --force..
        /// </summary>
        public static string PidOptionDescription {
            get {
                return ResourceManager.GetString("PidOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path to the Aspire AppHost project file or a directory to search.
        /// </summary>
        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The experimental tray protocol requires --protocol-version 1 --format json --apphost with an absolute file path, a positive --pid, and a positive --started-at in Unix milliseconds. --all and --force are not allowed..
        /// </summary>
        public static string ProtocolRequiresExactIdentity {
            get {
                return ResourceManager.GetString("ProtocolRequiresExactIdentity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending stop signal to {0}....
        /// </summary>
        public static string SendingStopSignal {
            get {
                return ResourceManager.GetString("SendingStopSignal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopping {0}....
        /// </summary>
        public static string StoppingAppHost {
            get {
                return ResourceManager.GetString("StoppingAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to an unknown version.
        /// </summary>
        public static string UnknownAspireHostingVersion {
            get {
                return ResourceManager.GetString("UnknownAspireHostingVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also remove persistent volumes created by Aspire (requires --force).
        /// </summary>
        public static string VolumesOptionDescription {
            get {
                return ResourceManager.GetString("VolumesOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} option requires the {1} option..
        /// </summary>
        public static string VolumesRequiresForce {
            get {
                return ResourceManager.GetString("VolumesRequiresForce", resourceCulture);
            }
        }
    }
}
