//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelemetryCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelemetryCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.TelemetryCommandStrings", typeof(TelemetryCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API key for authenticating with the dashboard (optional, for dashboards with API key authentication).
        /// </summary>
        internal static string ApiKeyOptionDescription {
            get {
                return ResourceManager.GetString("ApiKeyOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the configured dashboard.
        /// </summary>
        internal static string ConfiguredDashboardDisplayValue {
            get {
                return ResourceManager.GetString("ConfiguredDashboardDisplayValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. The dashboard at &apos;{0}&apos; does not have the telemetry API enabled..
        /// </summary>
        internal static string DashboardApiNotEnabled {
            get {
                return ResourceManager.GetString("DashboardApiNotEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start the dashboard with &apos;aspire dashboard run&apos; or set Dashboard:Api:Enabled to true..
        /// </summary>
        internal static string DashboardApiNotEnabledHint {
            get {
                return ResourceManager.GetString("DashboardApiNotEnabledHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. Authentication failed..
        /// </summary>
        internal static string DashboardAuthFailed {
            get {
                return ResourceManager.GetString("DashboardAuthFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alternatively, allow anonymous access with &apos;aspire dashboard run --allow-anonymous&apos; or by setting the ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS environment variable to true..
        /// </summary>
        internal static string DashboardAuthFailedAnonymousHint {
            get {
                return ResourceManager.GetString("DashboardAuthFailedAnonymousHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authenticate with the dashboard either with a --dashboard-url including a valid login token (e.g. http://localhost:18888/login?t=TOKEN), or with an --api-key matching the dashboard&apos;s configured API key..
        /// </summary>
        internal static string DashboardAuthFailedHint {
            get {
                return ResourceManager.GetString("DashboardAuthFailedHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. Unable to connect to &apos;{0}&apos;..
        /// </summary>
        internal static string DashboardConnectionFailed {
            get {
                return ResourceManager.GetString("DashboardConnectionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verify the dashboard is running and the URL is correct..
        /// </summary>
        internal static string DashboardConnectionFailedHint {
            get {
                return ResourceManager.GetString("DashboardConnectionFailedHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection to the dashboard was lost..
        /// </summary>
        internal static string DashboardConnectionLost {
            get {
                return ResourceManager.GetString("DashboardConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. The login token in the URL is invalid or expired..
        /// </summary>
        internal static string DashboardLoginTokenFailed {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alternatively, allow anonymous access with &apos;aspire dashboard run --allow-anonymous&apos; or by setting the ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS environment variable to true..
        /// </summary>
        internal static string DashboardLoginTokenFailedAnonymousHint {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailedAnonymousHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ensure you are using the login URL from the currently running dashboard instance..
        /// </summary>
        internal static string DashboardLoginTokenFailedHint {
            get {
                return ResourceManager.GetString("DashboardLoginTokenFailedHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. The dashboard is not available..
        /// </summary>
        internal static string DashboardNotAvailable {
            get {
                return ResourceManager.GetString("DashboardNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ensure the AppHost is running with the dashboard enabled..
        /// </summary>
        internal static string DashboardNotAvailableHint {
            get {
                return ResourceManager.GetString("DashboardNotAvailableHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --dashboard-url and --apphost options cannot be used together. Specify one or the other..
        /// </summary>
        internal static string DashboardUrlAndAppHostExclusive {
            get {
                return ResourceManager.GetString("DashboardUrlAndAppHostExclusive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. The value &apos;{0}&apos; is not a valid URL..
        /// </summary>
        internal static string DashboardUrlInvalid {
            get {
                return ResourceManager.GetString("DashboardUrlInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify an absolute URL like &apos;http://localhost:18888&apos;..
        /// </summary>
        internal static string DashboardUrlInvalidHint {
            get {
                return ResourceManager.GetString("DashboardUrlInvalidHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not fetch telemetry data from the dashboard. The specified URL &apos;{0}&apos; does not appear to be a valid dashboard address..
        /// </summary>
        internal static string DashboardUrlNotReachable {
            get {
                return ResourceManager.GetString("DashboardUrlNotReachable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verify the URL is correct..
        /// </summary>
        internal static string DashboardUrlNotReachableHint {
            get {
                return ResourceManager.GetString("DashboardUrlNotReachableHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base URL of a standalone Aspire Dashboard (e.g. http://localhost:18888). Login URLs are also accepted and automatically normalized..
        /// </summary>
        internal static string DashboardUrlOptionDescription {
            get {
                return ResourceManager.GetString("DashboardUrlOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View OpenTelemetry data (logs, spans, traces) from a running AppHost.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch telemetry: {0}.
        /// </summary>
        internal static string FailedToFetchTelemetry {
            get {
                return ResourceManager.GetString("FailedToFetchTelemetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stream telemetry in real-time as it arrives.
        /// </summary>
        internal static string FollowOptionDescription {
            get {
                return ResourceManager.GetString("FollowOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json).
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter by error status (true to show only errors, false to exclude errors).
        /// </summary>
        internal static string HasErrorOptionDescription {
            get {
                return ResourceManager.GetString("HasErrorOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string HeaderDuration {
            get {
                return ResourceManager.GetString("HeaderDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spans.
        /// </summary>
        internal static string HeaderSpans {
            get {
                return ResourceManager.GetString("HeaderSpans", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string HeaderTimestamp {
            get {
                return ResourceManager.GetString("HeaderTimestamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not an absolute HTTP(S) URL.
        /// </summary>
        internal static string InvalidDashboardUrlDisplayValue {
            get {
                return ResourceManager.GetString("InvalidDashboardUrlDisplayValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The --limit value must be a positive number..
        /// </summary>
        internal static string LimitMustBePositive {
            get {
                return ResourceManager.GetString("LimitMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum number of items to return.
        /// </summary>
        internal static string LimitOptionDescription {
            get {
                return ResourceManager.GetString("LimitOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View structured logs from the Dashboard telemetry API.
        /// </summary>
        internal static string LogsDescription {
            get {
                return ResourceManager.GetString("LogsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter by resource name.
        /// </summary>
        internal static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search and filter telemetry fields such as log messages, attribute values, names, source, and IDs. Supports full-text search and field filters. See https://aka.ms/aspire/cli-search for more details.
        /// </summary>
        internal static string SearchOptionDescription {
            get {
                return ResourceManager.GetString("SearchOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to view telemetry for.
        /// </summary>
        internal static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter logs by minimum severity (Trace, Debug, Information, Warning, Error, Critical).
        /// </summary>
        internal static string SeverityOptionDescription {
            get {
                return ResourceManager.GetString("SeverityOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View spans from the Dashboard telemetry API.
        /// </summary>
        internal static string SpansDescription {
            get {
                return ResourceManager.GetString("SpansDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The trace ID to view. If not specified, lists all traces..
        /// </summary>
        internal static string TraceIdArgumentDescription {
            get {
                return ResourceManager.GetString("TraceIdArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter by trace ID.
        /// </summary>
        internal static string TraceIdOptionDescription {
            get {
                return ResourceManager.GetString("TraceIdOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trace with ID &apos;{0}&apos; was not found..
        /// </summary>
        internal static string TraceNotFound {
            get {
                return ResourceManager.GetString("TraceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View traces from the Dashboard telemetry API.
        /// </summary>
        internal static string TracesDescription {
            get {
                return ResourceManager.GetString("TracesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard API returned unexpected content type &apos;{0}&apos;. Expected JSON response..
        /// </summary>
        internal static string UnexpectedContentType {
            get {
                return ResourceManager.GetString("UnexpectedContentType", resourceCulture);
            }
        }
    }
}
