//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.TerminalCommandStrings", typeof(TerminalCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovering terminal sessions....
        /// </summary>
        public static string DiscoveringSessions {
            get {
                return ResourceManager.GetString("DiscoveringSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looking up resource....
        /// </summary>
        public static string LookingUpResource {
            get {
                return ResourceManager.GetString("LookingUpResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (exited code={1}).
        /// </summary>
        public static string ReplicaExited {
            get {
                return ResourceManager.GetString("ReplicaExited", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replica index {0} is not available for resource &apos;{1}&apos;. Available indices: {2}..
        /// </summary>
        public static string ReplicaNotFound {
            get {
                return ResourceManager.GetString("ReplicaNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The 0-based replica index. Required for replicated resources in non-interactive mode..
        /// </summary>
        public static string ReplicaOptionDescription {
            get {
                return ResourceManager.GetString("ReplicaOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; has {1} replicas. Pass --replica &lt;index&gt; to choose one in non-interactive mode..
        /// </summary>
        public static string ReplicaRequired {
            get {
                return ResourceManager.GetString("ReplicaRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (running).
        /// </summary>
        public static string ReplicaRunning {
            get {
                return ResourceManager.GetString("ReplicaRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the resource whose terminal runs the tape..
        /// </summary>
        public static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A resource name is required..
        /// </summary>
        public static string ResourceRequired {
            get {
                return ResourceManager.GetString("ResourceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a replica of &apos;{0}&apos; to attach to:.
        /// </summary>
        public static string SelectReplica {
            get {
                return ResourceManager.GetString("SelectReplica", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The terminal connection closed before tape playback completed..
        /// </summary>
        public static string TapeConnectionClosed {
            get {
                return ResourceManager.GetString("TapeConnectionClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run VHS tape scripts against resource terminals..
        /// </summary>
        public static string TapeDescription {
            get {
                return ResourceManager.GetString("TapeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path to the VHS .tape file to play..
        /// </summary>
        public static string TapeFileDescription {
            get {
                return ResourceManager.GetString("TapeFileDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read tape file &apos;{0}&apos;: {1}.
        /// </summary>
        public static string TapeFileReadFailed {
            get {
                return ResourceManager.GetString("TapeFileReadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tape playback failed: {0}.
        /// </summary>
        public static string TapePlaybackFailed {
            get {
                return ResourceManager.GetString("TapePlaybackFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play a VHS tape against a running resource terminal and print its final screen..
        /// </summary>
        public static string TapePlayDescription {
            get {
                return ResourceManager.GetString("TapePlayDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to play a terminal tape.
        /// </summary>
        public static string TapeSelectAppHostAction {
            get {
                return ResourceManager.GetString("TapeSelectAppHostAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal tape playback did not finish within {0} seconds..
        /// </summary>
        public static string TapeTimeout {
            get {
                return ResourceManager.GetString("TapeTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum time in seconds to connect and play the tape. Defaults to 120 seconds..
        /// </summary>
        public static string TapeTimeoutDescription {
            get {
                return ResourceManager.GetString("TapeTimeoutDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The timeout must be between 1 and {0} seconds..
        /// </summary>
        public static string TapeTimeoutInvalid {
            get {
                return ResourceManager.GetString("TapeTimeoutInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connected AppHost does not support &apos;aspire terminal&apos;. Update Aspire.Hosting to 13.4 or later..
        /// </summary>
        public static string TerminalIncompatible {
            get {
                return ResourceManager.GetString("TerminalIncompatible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; is not available for terminal attachment. Make sure the resource was registered with &apos;.WithTerminal()&apos; and that the terminal host has started..
        /// </summary>
        public static string TerminalUnavailable {
            get {
                return ResourceManager.GetString("TerminalUnavailable", resourceCulture);
            }
        }
    }
}
