//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrayCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrayCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.TrayCommandStrings", typeof(TrayCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The experimental Aspire tray requires a leased, versioned CLI bundle. No usable bundle was found. Install a Windows or macOS Aspire bundle that includes the tray companion..
        /// </summary>
        public static string BundleRequired {
            get {
                return ResourceManager.GetString("BundleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage the Windows or macOS tray companion (Experimental).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire tray &apos;{0}&apos; helper failed with exit code {1}..
        /// </summary>
        public static string HelperFailed {
            get {
                return ResourceManager.GetString("HelperFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire tray &apos;{0}&apos; helper did not acknowledge completion within 30 seconds..
        /// </summary>
        public static string HelperTimedOut {
            get {
                return ResourceManager.GetString("HelperTimedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting the experimental tray requires an installed native Aspire CLI executable. Managed development builds and &apos;dotnet aspire.dll&apos; are not supported..
        /// </summary>
        public static string NativeCliRequired {
            get {
                return ResourceManager.GetString("NativeCliRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not complete Aspire tray &apos;{0}&apos;: {1}.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The CLI bundle does not contain the tray companion for this platform (Windows: tray/aspire-tray.exe and tray/Aspire.ico; macOS: tray/Aspire Tray.app). Install a matching native Aspire bundle, or run &apos;aspire setup --force&apos; to repair an incomplete extraction..
        /// </summary>
        public static string PayloadMissing {
            get {
                return ResourceManager.GetString("PayloadMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start or restore the tray icon (Experimental).
        /// </summary>
        public static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The experimental Aspire tray is ready..
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the tray without stopping AppHosts (Experimental).
        /// </summary>
        public static string StopDescription {
            get {
                return ResourceManager.GetString("StopDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Aspire tray is stopped. AppHosts were not stopped..
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The experimental Aspire tray supports Windows and macOS x64/ARM64 installations. Linux is not supported..
        /// </summary>
        public static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
    }
}
