//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.UpdateCommandStrings", typeof(UpdateCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added: {0}.
        /// </summary>
        internal static string AddedFeedFormat {
            get {
                return ResourceManager.GetString("AddedFeedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyze AppHost.
        /// </summary>
        internal static string AnalyzeAppHost {
            get {
                return ResourceManager.GetString("AnalyzeAppHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyze AppHost SDK.
        /// </summary>
        internal static string AnalyzeAppHostSdk {
            get {
                return ResourceManager.GetString("AnalyzeAppHostSdk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyze project: {0}.
        /// </summary>
        internal static string AnalyzeProjectFormat {
            get {
                return ResourceManager.GetString("AnalyzeProjectFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyzing project....
        /// </summary>
        internal static string AnalyzingProjectStatus {
            get {
                return ResourceManager.GetString("AnalyzingProjectStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply these changes to NuGet.config?.
        /// </summary>
        internal static string ApplyChangesToNuGetConfig {
            get {
                return ResourceManager.GetString("ApplyChangesToNuGetConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applying updates....
        /// </summary>
        internal static string ApplyingUpdates {
            get {
                return ResourceManager.GetString("ApplyingUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Central package management is currently not supported by &apos;aspire update&apos;..
        /// </summary>
        internal static string CentralPackageManagementNotSupported {
            get {
                return ResourceManager.GetString("CentralPackageManagementNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string ChannelNonePlaceholder {
            get {
                return ResourceManager.GetString("ChannelNonePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel to update to (stable, daily).
        /// </summary>
        internal static string ChannelOptionDescription {
            get {
                return ResourceManager.GetString("ChannelOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel to update to (stable, staging, daily).
        /// </summary>
        internal static string ChannelOptionDescriptionWithStaging {
            get {
                return ResourceManager.GetString("ChannelOptionDescriptionWithStaging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find PackageVersion element for &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string CouldNotFindPackageVersionInDirectoryPackagesProps {
            get {
                return ResourceManager.GetString("CouldNotFindPackageVersionInDirectoryPackagesProps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find root &lt;Project&gt; element in {0}.
        /// </summary>
        internal static string CouldNotFindRootProjectElementFormat {
            get {
                return ResourceManager.GetString("CouldNotFindRootProjectElementFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find &lt;Sdk Name=&apos;Aspire.AppHost.Sdk&apos; /&gt; element in {0}.
        /// </summary>
        internal static string CouldNotFindSdkElementFormat {
            get {
                return ResourceManager.GetString("CouldNotFindSdkElementFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update integrations and repository Aspire CLI references.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To update the Aspire CLI when installed as a .NET tool, run:.
        /// </summary>
        internal static string DotNetToolSelfUpdateMessage {
            get {
                return ResourceManager.GetString("DotNetToolSelfUpdateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executing: {0}.
        /// </summary>
        internal static string ExecutingUpdateStepFormat {
            get {
                return ResourceManager.GetString("ExecutingUpdateStepFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extracted new CLI.
        /// </summary>
        internal static string ExtractedNewCli {
            get {
                return ResourceManager.GetString("ExtractedNewCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extracting new CLI....
        /// </summary>
        internal static string ExtractingNewCli {
            get {
                return ResourceManager.GetString("ExtractingNewCli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to discover NuGet.config files..
        /// </summary>
        internal static string FailedDiscoverNuGetConfig {
            get {
                return ResourceManager.GetString("FailedDiscoverNuGetConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch items and properties for project: {0}.
        /// </summary>
        internal static string FailedFetchItemsAndPropertiesFormat {
            get {
                return ResourceManager.GetString("FailedFetchItemsAndPropertiesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read tool manifest &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedReadToolManifestFormat {
            get {
                return ResourceManager.GetString("FailedReadToolManifestFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not resolve @microsoft/aspire-cli@{0} from npm. Check that npm is available and this version is published. Repository tool manifests were not changed..
        /// </summary>
        internal static string FailedResolveNpmToolFormat {
            get {
                return ResourceManager.GetString("FailedResolveNpmToolFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to restore packages for project {0} after update..
        /// </summary>
        internal static string FailedToRestoreAfterUpdateFormat {
            get {
                return ResourceManager.GetString("FailedToRestoreAfterUpdateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to update package reference for {0} in project {1}..
        /// </summary>
        internal static string FailedUpdatePackageReferenceFormat {
            get {
                return ResourceManager.GetString("FailedUpdatePackageReferenceFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note: Update plan generated using fallback parsing due to unresolvable AppHost SDK. Dependency analysis may have reduced accuracy..
        /// </summary>
        internal static string FallbackParsingWarning {
            get {
                return ResourceManager.GetString("FallbackParsingWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to    Mapping: {0} (added).
        /// </summary>
        internal static string MappingAddedFormat {
            get {
                return ResourceManager.GetString("MappingAddedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to    Mapping: {0} (removed).
        /// </summary>
        internal static string MappingRemovedFormat {
            get {
                return ResourceManager.GetString("MappingRemovedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to    Mapping: {0}.
        /// </summary>
        internal static string MappingRetainedFormat {
            get {
                return ResourceManager.GetString("MappingRetainedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Migrated to new project format: &lt;Project Sdk=&quot;Aspire.AppHost.Sdk/{0}&quot;&gt;.
        /// </summary>
        internal static string MigratedToNewSdkFormat {
            get {
                return ResourceManager.GetString("MigratedToNewSdkFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply any pending migrations to the project after updating its packages..
        /// </summary>
        internal static string MigrateOptionDescription {
            get {
                return ResourceManager.GetString("MigrateOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The project packages were updated, but applying migrations failed. Run &apos;aspire update --migrate&apos; again to retry..
        /// </summary>
        internal static string MigrationApplyFailedWarning {
            get {
                return ResourceManager.GetString("MigrationApplyFailedWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To update the Aspire CLI when installed from Nix, update the profile package or flake input:.
        /// </summary>
        internal static string NixSelfUpdateMessage {
            get {
                return ResourceManager.GetString("NixSelfUpdateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Aspire AppHost project found. Would you like to update the Aspire CLI instead?.
        /// </summary>
        internal static string NoAppHostFoundUpdateCliPrompt {
            get {
                return ResourceManager.GetString("NoAppHostFoundUpdateCliPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No changes detected in NuGet.config.
        /// </summary>
        internal static string NoChangesDetectedInNuGetConfig {
            get {
                return ResourceManager.GetString("NoChangesDetectedInNuGetConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No channel found matching &apos;{0}&apos;. Valid options are: {1}..
        /// </summary>
        internal static string NoChannelFoundMatching {
            get {
                return ResourceManager.GetString("NoChannelFoundMatching", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No package found with ID &apos;{0}&apos; in channel &apos;{1}&apos;..
        /// </summary>
        internal static string NoPackageFoundFormat {
            get {
                return ResourceManager.GetString("NoPackageFoundFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot write to installation directory &apos;{0}&apos;. Please run the update with elevated permissions (e.g., using sudo on Linux/macOS)..
        /// </summary>
        internal static string NoWritePermissionToInstallDirectory {
            get {
                return ResourceManager.GetString("NoWritePermissionToInstallDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To update the Aspire CLI when installed from npm, run:.
        /// </summary>
        internal static string NpmSelfUpdateMessage {
            get {
                return ResourceManager.GetString("NpmSelfUpdateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory to create or update the NuGet.config file in.
        /// </summary>
        internal static string NuGetConfigDirOptionDescription {
            get {
                return ResourceManager.GetString("NuGetConfigDirOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No package found with ID &apos;{0}&apos; in channel &apos;{1}&apos;. Skipping..
        /// </summary>
        internal static string PackageNotFoundInChannelWarningFormat {
            get {
                return ResourceManager.GetString("PackageNotFoundInChannelWarningFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package reference does not have Identity..
        /// </summary>
        internal static string PackageReferenceNoIdentity {
            get {
                return ResourceManager.GetString("PackageReferenceNoIdentity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package reference does not have Version..
        /// </summary>
        internal static string PackageReferenceNoVersion {
            get {
                return ResourceManager.GetString("PackageReferenceNoVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This project has pending migrations:.
        /// </summary>
        internal static string PendingMigrationsHeader {
            get {
                return ResourceManager.GetString("PendingMigrationsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run &apos;aspire update --migrate&apos; to apply them..
        /// </summary>
        internal static string PendingMigrationsHint {
            get {
                return ResourceManager.GetString("PendingMigrationsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perform updates?.
        /// </summary>
        internal static string PerformUpdatesPrompt {
            get {
                return ResourceManager.GetString("PerformUpdatesPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path to the Aspire AppHost project file or a directory to search.
        /// </summary>
        internal static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project reference does not have FullPath..
        /// </summary>
        internal static string ProjectReferenceNoFullPath {
            get {
                return ResourceManager.GetString("ProjectReferenceNoFullPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project update skipped. Update the Aspire CLI, then re-run `aspire update`..
        /// </summary>
        internal static string ProjectUpdateSkippedAfterCliUpdateMessage {
            get {
                return ResourceManager.GetString("ProjectUpdateSkippedAfterCliUpdateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project is up to date! (no updates necessary).
        /// </summary>
        internal static string ProjectUpToDateMessage {
            get {
                return ResourceManager.GetString("ProjectUpToDateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality level to update to (stable, daily).
        /// </summary>
        internal static string QualityOptionDescription {
            get {
                return ResourceManager.GetString("QualityOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quality level to update to (stable, staging, daily).
        /// </summary>
        internal static string QualityOptionDescriptionWithStaging {
            get {
                return ResourceManager.GetString("QualityOptionDescriptionWithStaging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerated SDK code with updated packages..
        /// </summary>
        internal static string RegeneratedSdkCode {
            get {
                return ResourceManager.GetString("RegeneratedSdkCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerating SDK code with updated packages....
        /// </summary>
        internal static string RegeneratingSdkCode {
            get {
                return ResourceManager.GetString("RegeneratingSdkCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed: {0}.
        /// </summary>
        internal static string RemovedFeedFormat {
            get {
                return ResourceManager.GetString("RemovedFeedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed obsolete Aspire.Hosting.AppHost package reference.
        /// </summary>
        internal static string RemovedObsoleteAppHostPackage {
            get {
                return ResourceManager.GetString("RemovedObsoleteAppHostPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository Aspire CLI references updated. The running CLI was not replaced..
        /// </summary>
        internal static string RepositoryToolsUpdated {
            get {
                return ResourceManager.GetString("RepositoryToolsUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repository Aspire CLI references are up to date..
        /// </summary>
        internal static string RepositoryToolsUpToDate {
            get {
                return ResourceManager.GetString("RepositoryToolsUpToDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: [bold yellow]{1}[/] [bold green]{2}[/] to [bold green]{3}[/].
        /// </summary>
        internal static string RepositoryToolUpdateFormat {
            get {
                return ResourceManager.GetString("RepositoryToolUpdateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run &apos;dotnet tool restore&apos; in the repository to use the updated .NET tool. Ensure its NuGet configuration includes the selected channel&apos;s feed..
        /// </summary>
        internal static string RestoreRepositoryDotNetTool {
            get {
                return ResourceManager.GetString("RestoreRepositoryDotNetTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lockfiles were not changed. Run your package manager&apos;s install command (for example, &apos;npm install&apos;) to refresh the lockfile and use the updated npm tool..
        /// </summary>
        internal static string RestoreRepositoryNpmTool {
            get {
                return ResourceManager.GetString("RestoreRepositoryNpmTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restoring packages....
        /// </summary>
        internal static string RestoringPackagesAfterUpdate {
            get {
                return ResourceManager.GetString("RestoringPackagesAfterUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retained: {0}.
        /// </summary>
        internal static string RetainedFeedFormat {
            get {
                return ResourceManager.GetString("RetainedFeedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string SdkVersionUnknownPlaceholder {
            get {
                return ResourceManager.GetString("SdkVersionUnknownPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a channel:.
        /// </summary>
        internal static string SelectChannelPrompt {
            get {
                return ResourceManager.GetString("SelectChannelPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update the Aspire CLI itself to the latest version.
        /// </summary>
        internal static string SelfOptionDescription {
            get {
                return ResourceManager.GetString("SelfOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The tool manifest &apos;{0}&apos; changed during update. Run &apos;aspire update&apos; again..
        /// </summary>
        internal static string ToolManifestChangedFormat {
            get {
                return ResourceManager.GetString("ToolManifestChangedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping the Aspire CLI reference in &apos;{0}&apos;: &apos;{1}&apos; is not an exact version or a simple ^/~ version range..
        /// </summary>
        internal static string UnsupportedToolVersionFormat {
            get {
                return ResourceManager.GetString("UnsupportedToolVersionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected code path..
        /// </summary>
        internal static string UnexpectedCodePath {
            get {
                return ResourceManager.GetString("UnexpectedCodePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update aspire.config.json channel from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string UpdateChannelStepDescriptionFormat {
            get {
                return ResourceManager.GetString("UpdateChannelStepDescriptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An update is available for the Aspire CLI. Would you like to update it now?.
        /// </summary>
        internal static string UpdateCliAfterProjectUpdatePrompt {
            get {
                return ResourceManager.GetString("UpdateCliAfterProjectUpdatePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected Aspire SDK is newer than this Aspire CLI. Update the Aspire CLI now and re-run `aspire update` to update this project?.
        /// </summary>
        internal static string UpdateCliBeforeGuestProjectUpdatePrompt {
            get {
                return ResourceManager.GetString("UpdateCliBeforeGuestProjectUpdatePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update package {0} from {1} to {2}.
        /// </summary>
        internal static string UpdatePackageFormat {
            get {
                return ResourceManager.GetString("UpdatePackageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update repository Aspire CLI references.
        /// </summary>
        internal static string UpdateRepositoryTools {
            get {
                return ResourceManager.GetString("UpdateRepositoryTools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update successful!.
        /// </summary>
        internal static string UpdateSuccessfulMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessfulMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Which directory for NuGet.config file?.
        /// </summary>
        internal static string WhichDirectoryNuGetConfigPrompt {
            get {
                return ResourceManager.GetString("WhichDirectoryNuGetConfigPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically confirm all update prompts without asking.
        /// </summary>
        internal static string YesOptionDescription {
            get {
                return ResourceManager.GetString("YesOptionDescription", resourceCulture);
            }
        }
    }
}
