//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WaitCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WaitCommandStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.WaitCommandStrings", typeof(WaitCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wait for a resource to reach a target status.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid status value &apos;{0}&apos;. Valid values are: healthy, up, down..
        /// </summary>
        public static string InvalidStatusValue {
            get {
                return ResourceManager.GetString("InvalidStatusValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name of the resource to wait for.
        /// </summary>
        public static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; entered a failed state: {1}.
        /// </summary>
        public static string ResourceEnteredFailedState {
            get {
                return ResourceManager.GetString("ResourceEnteredFailedState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; is {1}. ({2:F1}s).
        /// </summary>
        public static string ResourceReachedTargetStatus {
            get {
                return ResourceManager.GetString("ResourceReachedTargetStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to connect to.
        /// </summary>
        public static string SelectAppHostAction {
            get {
                return ResourceManager.GetString("SelectAppHostAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The target status to wait for (healthy, up, down). Defaults to healthy..
        /// </summary>
        public static string StatusOptionDescription {
            get {
                return ResourceManager.GetString("StatusOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout must be a positive number of seconds..
        /// </summary>
        public static string TimeoutMustBePositive {
            get {
                return ResourceManager.GetString("TimeoutMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum time to wait in seconds. Defaults to 120..
        /// </summary>
        public static string TimeoutOptionDescription {
            get {
                return ResourceManager.GetString("TimeoutOptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting for resource &apos;{0}&apos; to be {1}....
        /// </summary>
        public static string WaitingForResource {
            get {
                return ResourceManager.GetString("WaitingForResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for resource &apos;{0}&apos; to be {1} after {2}s..
        /// </summary>
        public static string WaitTimedOut {
            get {
                return ResourceManager.GetString("WaitTimedOut", resourceCulture);
            }
        }
    }
}
