//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.TerminalStrings", typeof(TerminalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle terminal (`).
        /// </summary>
        public static string MainLayoutToggleTerminalDock {
            get {
                return ResourceManager.GetString("MainLayoutToggleTerminalDock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not copy to clipboard..
        /// </summary>
        public static string TerminalCopyFailed {
            get {
                return ResourceManager.GetString("TerminalCopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy terminal title: {0}.
        /// </summary>
        public static string TerminalCopyTitle {
            get {
                return ResourceManager.GetString("TerminalCopyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy working directory: {0}.
        /// </summary>
        public static string TerminalCopyWorkingDirectory {
            get {
                return ResourceManager.GetString("TerminalCopyWorkingDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The terminal disconnected and automatic retries have stopped. Check that the resource is running, then retry..
        /// </summary>
        public static string TerminalDisconnected {
            get {
                return ResourceManager.GetString("TerminalDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string TerminalDismissError {
            get {
                return ResourceManager.GetString("TerminalDismissError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close terminal &apos;{0}&apos;.
        /// </summary>
        public static string TerminalDockCloseTab {
            get {
                return ResourceManager.GetString("TerminalDockCloseTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for terminal &apos;{0}&apos; to shut down. Cleanup is continuing in the background..
        /// </summary>
        public static string TerminalDockCloseTimedOutMessage {
            get {
                return ResourceManager.GetString("TerminalDockCloseTimedOutMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal close timed out.
        /// </summary>
        public static string TerminalDockCloseTimedOutTitle {
            get {
                return ResourceManager.GetString("TerminalDockCloseTimedOutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open terminal in a new window.
        /// </summary>
        public static string TerminalDockDetach {
            get {
                return ResourceManager.GetString("TerminalDockDetach", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The browser blocked the terminal window. Allow pop-ups for the dashboard and try again..
        /// </summary>
        public static string TerminalDockDetachBlocked {
            get {
                return ResourceManager.GetString("TerminalDockDetachBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal is running in a separate window..
        /// </summary>
        public static string TerminalDockDetached {
            get {
                return ResourceManager.GetString("TerminalDockDetached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus window.
        /// </summary>
        public static string TerminalDockFocusWindow {
            get {
                return ResourceManager.GetString("TerminalDockFocusWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} pixels high.
        /// </summary>
        public static string TerminalDockHeight {
            get {
                return ResourceManager.GetString("TerminalDockHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide terminal panel (`).
        /// </summary>
        public static string TerminalDockHide {
            get {
                return ResourceManager.GetString("TerminalDockHide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string TerminalDockMoreInformation {
            get {
                return ResourceManager.GetString("TerminalDockMoreInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No docked terminals.
        /// </summary>
        public static string TerminalDockPanelHeading {
            get {
                return ResourceManager.GetString("TerminalDockPanelHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press the backtick key (`) to hide this panel..
        /// </summary>
        public static string TerminalDockPanelHint {
            get {
                return ResourceManager.GetString("TerminalDockPanelHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal may still be open in a separate window. Focus it or return it to the panel to continue..
        /// </summary>
        public static string TerminalDockRecoveringWindow {
            get {
                return ResourceManager.GetString("TerminalDockRecoveringWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder tabs, or use Alt+Shift+Left or Alt+Shift+Right while a tab is focused..
        /// </summary>
        public static string TerminalDockReorderHelp {
            get {
                return ResourceManager.GetString("TerminalDockReorderHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Up or Down to resize, Shift for larger steps, Home for minimum height, and End for maximum height..
        /// </summary>
        public static string TerminalDockResizeHelp {
            get {
                return ResourceManager.GetString("TerminalDockResizeHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return to panel.
        /// </summary>
        public static string TerminalDockReturnToDock {
            get {
                return ResourceManager.GetString("TerminalDockReturnToDock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll terminal tabs left.
        /// </summary>
        public static string TerminalDockScrollLeft {
            get {
                return ResourceManager.GetString("TerminalDockScrollLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll terminal tabs right.
        /// </summary>
        public static string TerminalDockScrollRight {
            get {
                return ResourceManager.GetString("TerminalDockScrollRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string TerminalDockTabs {
            get {
                return ResourceManager.GetString("TerminalDockTabs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus terminal controls.
        /// </summary>
        public static string TerminalFocusControlsDescription {
            get {
                return ResourceManager.GetString("TerminalFocusControlsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The terminal could not complete the input or clipboard action. Check browser clipboard permissions and try again..
        /// </summary>
        public static string TerminalInputFailed {
            get {
                return ResourceManager.GetString("TerminalInputFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interactive terminal input.
        /// </summary>
        public static string TerminalInputLabel {
            get {
                return ResourceManager.GetString("TerminalInputLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The terminal could not connect or initialize its renderer. Check that the resource is running and your browser supports WebGPU or WebGL2, then reconnect to try again. You can still view this resource&apos;s console logs..
        /// </summary>
        public static string TerminalMountFailed {
            get {
                return ResourceManager.GetString("TerminalMountFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal palette.
        /// </summary>
        public static string TerminalPalette {
            get {
                return ResourceManager.GetString("TerminalPalette", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string TerminalPaletteDark {
            get {
                return ResourceManager.GetString("TerminalPaletteDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string TerminalPaletteLabel {
            get {
                return ResourceManager.GetString("TerminalPaletteLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string TerminalPaletteLight {
            get {
                return ResourceManager.GetString("TerminalPaletteLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to save the terminal palette. Check that browser storage is available and try again..
        /// </summary>
        public static string TerminalPaletteSaveFailed {
            get {
                return ResourceManager.GetString("TerminalPaletteSaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal progress.
        /// </summary>
        public static string TerminalProgress {
            get {
                return ResourceManager.GetString("TerminalProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TerminalProgressError {
            get {
                return ResourceManager.GetString("TerminalProgressError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TerminalProgressWarning {
            get {
                return ResourceManager.GetString("TerminalProgressWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reconnect terminal.
        /// </summary>
        public static string TerminalRetry {
            get {
                return ResourceManager.GetString("TerminalRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string TerminalsHeader {
            get {
                return ResourceManager.GetString("TerminalsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TerminalSizeLabel {
            get {
                return ResourceManager.GetString("TerminalSizeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The terminal could not take resize control or change its dimensions. Try selecting the dimensions again..
        /// </summary>
        public static string TerminalSizingFailed {
            get {
                return ResourceManager.GetString("TerminalSizingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        public static string TerminalsPageTitle {
            get {
                return ResourceManager.GetString("TerminalsPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a resource to view its terminal.
        /// </summary>
        public static string TerminalsSelectAResource {
            get {
                return ResourceManager.GetString("TerminalsSelectAResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select resource.
        /// </summary>
        public static string TerminalsSelectResourceToolbar {
            get {
                return ResourceManager.GetString("TerminalsSelectResourceToolbar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View options.
        /// </summary>
        public static string TerminalsSettings {
            get {
                return ResourceManager.GetString("TerminalsSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string TerminalTitle {
            get {
                return ResourceManager.GetString("TerminalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decrease font size.
        /// </summary>
        public static string TerminalToolbarDecreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarDecreaseFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal dimensions.
        /// </summary>
        public static string TerminalToolbarGridSize {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fit terminal to available space.
        /// </summary>
        public static string TerminalToolbarGridSizeAuto {
            get {
                return ResourceManager.GetString("TerminalToolbarGridSizeAuto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Increase font size.
        /// </summary>
        public static string TerminalToolbarIncreaseFontSize {
            get {
                return ResourceManager.GetString("TerminalToolbarIncreaseFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        public static string TerminalToolbarOpenInWindow {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The browser blocked the terminal window. Allow pop-ups for this site and try again..
        /// </summary>
        public static string TerminalToolbarOpenInWindowBlocked {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowBlocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to open the terminal window. Reload the dashboard and try again..
        /// </summary>
        public static string TerminalToolbarOpenInWindowFailed {
            get {
                return ResourceManager.GetString("TerminalToolbarOpenInWindowFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This terminal has ended..
        /// </summary>
        public static string TerminalWindowEnded {
            get {
                return ResourceManager.GetString("TerminalWindowEnded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to recover the terminal window state. Check browser storage permissions, reload, or explicitly return the terminal to the panel..
        /// </summary>
        public static string TerminalWindowTrackingFailed {
            get {
                return ResourceManager.GetString("TerminalWindowTrackingFailed", resourceCulture);
            }
        }
    }
}
