name: 🐞Failing test on CI
description: Create a report about a failing test
title: "[Failing test]: "
labels: [ 'blocking-clean-ci' ]
body:
  - type: markdown
    attributes:
      value: |
        Test(s) failing on a Azdo CI run. This issue will track the failures on Azdo using the [Known Issues infrastructure](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the failure you encountered ([aspire/issues](https://github.com/dotnet/aspire/issues)). More information on our issue management policies is available [here](https://aka.ms/aspnet/issue-policies).
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Build url
      description: Url for the failing build
    validations:
      required: true
    value: "Build: "
  - type: input
    attributes:
      label: Build error leg or test failing
      description: Name of the build job, or name of the failing test
    validations:
      required: false
    value: "Build error leg or test failing:"
  - type: inputs
    attributes:
      label: Pull Request
      description: Pull Request url (if any)
    validations:
      required: false
    value: "Pull Request:"
  - type: textarea
    attributes:
      label: Fill in the error message template
      value: |
        <!-- Error message template  -->
        ## Error Message

        Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

        <!-- Use ErrorMessage for String.Contains matches. Use ErrorPattern for regex matches (single line/no backtracking). Set BuildRetry to `true` to retry builds with this error. Set ExcludeConsoleLog to `true` to skip helix logs analysis. -->

        ```json
        {
          "ErrorMessage": "",
          "ErrorPattern": "",
          "BuildRetry": false,
          "ExcludeConsoleLog": false
        }
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other info
      description: Any other useful information about the failure
      placeholder:
    validations:
      required: false
