name: Compute results
description: Compute results
runs:
  using: "composite"
  steps:
    # get all the test-job-result* artifacts into a single directory
    - uses: actions/download-artifact@v4
      with:
        pattern: test-job-result-*
        merge-multiple: true
        path: test-job-result

    - uses: actions/download-artifact@v4
      with:
        pattern: logs-*-ubuntu-latest
        merge-multiple: true
        path: testresults/ubuntu-latest

    - uses: actions/download-artifact@v4
      with:
        pattern: logs-*-windows-latest
        merge-multiple: true
        path: testresults/windows-latest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Integration-TestResults
        path: testresults/**/*.trx

    # return success if zero result-failed-* files are found
    - name: Compute result
      run: |
        [ 0 -eq $(find test-job-result -name 'result-failed-*' | wc -l) ]
